added an option to skip failed outputs in agent startup
influxdata/telegraf pull request #10111
Opened 2021-11-16 10:59 UTC by eran-gil2

### Required for all PRs:

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

2021-11-16 11:00 UTC, eran-gil2 commented
!signed-cla

2021-11-17 10:19 UTC, eran-gil2 commented
hey could you please approve other workflows so this feature could be merged? :)

2021-11-21 09:25 UTC, eran-gil2 commented
@srebhan who is allowed to review my feature? anyone? or are there certain specifications for this?

2021-11-23 10:20 UTC, Hipska requested changes
General idea is good, but I would add a command line option for that as well.

It seems to me that it might be better if outputs that are not able to connect at startup are retried after some time instead of just being completely ignored for the duration of telegraf run.

2021-11-23 10:20 UTC, Hipska commented on config/config.go
> +	SkipFailedOutputs bool `toml:"skip_failed_outputs"`
Please also update related `agentConfig` with example configuration.

2021-11-23 10:32 UTC, Hipska commented
This PR also doesn't solve #3723 since it is requested to have x times or retry. This PR doesn't add this behaviour.

Comments in a related PR (#9051) mentioned that plugins should be implementing the `Start` or `Connect` method in order to let telegraf startup without halting if one of the plugins cannot be connected to. It seems that in order to have it like this, a change in agent.go needs to be done.

2021-11-23 12:36 UTC, srebhan commented
@eran-gil2 I'd like to discuss this with the core-devs as this is a very mighty feature IMO. To me it seems too easy to loose data when using this feature without caution as you will get an "everything alright" impression but you easily have no working output. I think this might be some fundamental thing to retry to connect to the outputs until we reach a buffer overflow or anything. We even might want to persist the metrics locally in this case...

2021-11-23 13:26 UTC, Hipska commented on config/config.go
> +	SkipFailedOutputs bool `toml:"skip_failed_outputs"`
As well as the `etc/telegraf.conf` and `etc/telegraf_windows.conf`

2022-06-22 12:34 UTC, closed without merging