fix: typo
influxdata/telegraf pull request #10361
Opened 2021-12-31 15:11 UTC by Howie59

### Required for all PRs:

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves NA

2021-12-31 15:13 UTC, Howie59 commented
!signed-cla

2022-01-04 15:17 UTC, sspaink requested changes
Thank you for resolving these typos! Just one suggested change, everything else looks good.

2022-01-04 15:17 UTC, sspaink commented on accumulator.go
> +	// SetPrecision sets the timestamp rounding precision.  All metrics adds
```suggestion
	// SetPrecision sets the timestamp rounding precision.  All metrics
```

2022-01-04 15:26 UTC, powersj commented
@Howie59 - how did you find all these?

2022-01-05 05:01 UTC, Howie59 commented on accumulator.go
> +	// SetPrecision sets the timestamp rounding precision.  All metrics adds
done

2022-01-05 05:02 UTC, Howie59 commented
> @Howie59 - how did you find all these?

i read the code of the entire process

2022-01-05 15:19 UTC, powersj approved these changes

2022-01-05 15:20 UTC, merged