feat: macOS wireless plugin
influxdata/telegraf pull request #10622
Opened 2022-02-10 13:28 UTC by davidgs

Adds support for monitoring wireless networks on macOS

2022-02-10 14:40 UTC, powersj commented
@davidgs,

Can you do two things:

1. Run `make fmt` and push again. There is an unused import.
2. Rebase on master, so your tests run on Windows. I put in a fix yesterday.

Thanks!

2022-02-10 17:53 UTC, davidgs commented
@powersj do the tests need to run on windows? The plug-in won't ever run there (since it's macOS only)

2022-02-10 19:58 UTC, Hipska commented
> I understand it would be nicer but it is much harder to do. I can look at it, but it will take longer.

No problem, take your time. 

Ps, next feature release is planned somewhere in March.

2022-02-16 09:10 UTC, Hipska requested changes
I see a lot of unrelated changes in this PR, these shouldn't exist in here. They also make reviewing a lot harder.

Please mark this PR as draft if you are not finished and do not expect reviews yet.

2022-02-16 09:10 UTC, Hipska commented on plugins/inputs/wireless/wireless_mac.go
> +		metrics, tags, err := w.loadMacWirelessTable(wireless, w.DumpZeros)
No need to pass `DumpZeros` as it is available inside the method as well..

2022-02-16 09:10 UTC, Hipska commented on plugins/inputs/wireless/wireless_mac.go
> +	metrics := strings.Split(string(string(table)), "\n")
Why is this double casting to string needed?

2022-02-16 09:10 UTC, Hipska commented on plugins/inputs/wireless/wireless_mac.go
> +		wg.Add(3)
Is this wait group actually needed? What does it add?

2022-02-16 09:10 UTC, Hipska commented on plugins/inputs/wireless/wireless_mac.go
> +}
init already exists in `wireless.go`

2022-02-16 09:10 UTC, Hipska commented on plugins/inputs/wireless/wireless_notlinux.go
> +// +build !linux,!darwin
Maybe rename this file to `wireless_notsupported.go`?

2022-02-16 13:21 UTC, davidgs commented
I'm closing this garbage PR and will resubmit.

2022-02-16 13:21 UTC, closed without merging

2022-02-16 13:24 UTC, Hipska commented
Well, actually it already looked better after this last merge..