docs: update how to generate sample config
influxdata/telegraf pull request #10831
Opened 2022-03-16 18:15 UTC by sspaink

2022-03-23 09:45 UTC, Hipska requested changes

2022-03-23 09:45 UTC, Hipska commented on docs/CONFIGURATION.md
> +telegraf --sample-config --input-filter cpu:mem:net:swap --output-filter influxdb:kafka config
```suggestion
telegraf --sample-config --input-filter cpu:mem:net:swap --output-filter influxdb:kafka
```

2022-03-23 15:57 UTC, Hipska commented on docs/CONFIGURATION.md
> +telegraf --sample-config --input-filter cpu:mem:net:swap --output-filter influxdb:kafka config
Yep 👍

2022-03-24 10:44 UTC, Hipska approved these changes
Note that the commands are also explained in other places:

https://github.com/influxdata/telegraf/blob/828b0400ac16a83ade37ed8632d330ca09e6115d/docs/COMMANDS_AND_FLAGS.md?plain=1#L46-L53

These need to be updated as well..

2022-03-24 13:09 UTC, MyaLongmire approved these changes

2022-03-24 21:17 UTC, sspaink commented
After some discussion closing this because this should be an issue so that the following works:
`telegraf config --input-filter cpu --output-filter influxdb`

instead of `telegraf --input-filter cpu --output-filter influxdb config`

`--sample-config` should probably be deprecated as well in favor of `config`

2022-03-24 21:17 UTC, closed without merging

2022-03-24 21:21 UTC, Hipska commented
According to the changes you made here, I assumed the `config` command would become deprecated.

2022-03-24 21:25 UTC, sspaink commented
I originally was in favor of doing it that way so sorry for the confusion, but looking at it again using `config` does seem like a more standard CLI way of doing things using a command followed by flags instead of a flag followed by more flags.

2022-03-25 05:55 UTC, Hipska commented
That makes more sense indeed!