feat(inputs.nginx_plus_api): Gather limit_reqs metrics
influxdata/telegraf pull request #10874
Opened 2022-03-23 09:41 UTC by glennlod

### Required for all PRs:

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

2022-06-29 17:38 UTC, sspaink approved these changes

2022-07-06 19:30 UTC, reimda requested changes

2022-07-07 06:50 UTC, glennlod commented on plugins/inputs/nginx_plus_api/nginx_plus_api_metrics.go
> +// Added in 6 API version
I added a link to the readme because this is a single documentation page for all NGINX API interfaces

2022-07-07 14:24 UTC, srebhan approved these changes
Looks good to me. Thanks for the quick response @glennlod!

2022-07-07 16:43 UTC, reimda approved these changes

2022-07-07 16:43 UTC, merged