fix: update starlark 7a1108eaa012->d1966c6b9fcd
influxdata/telegraf pull request #10940
Opened 2022-04-05 18:56 UTC by sspaink

resolve: https://github.com/influxdata/telegraf/issues/10828

Updating go.starlark.net to latest version, the project doesn't use official releases but we are using the latest commit. As suggested by @Hipska updated the spec as well to point to the commit instead of master.

@Hipska could you test out this change? thanks!

2022-04-06 07:05 UTC, Hipska requested changes
Looks good, only change the url for all references..

2022-04-06 07:05 UTC, Hipska commented on plugins/processors/starlark/README.md
>  [dict]: https://github.com/google/starlark-go/blob/master/doc/spec.md#dictionaries
```suggestion
[string]: https://github.com/google/starlark-go/blob/d1966c6b9fcd/doc/spec.md#strings
[dict]: https://github.com/google/starlark-go/blob/d1966c6b9fcd/doc/spec.md#dictionaries
```

2022-04-06 07:05 UTC, Hipska commented on plugins/aggregators/starlark/README.md
>  [dict]: https://github.com/google/starlark-go/blob/master/doc/spec.md#dictionaries
```suggestion
[dict]: https://github.com/google/starlark-go/blob/d1966c6b9fcd/doc/spec.md#dictionaries
```

2022-04-06 15:14 UTC, sspaink commented on plugins/processors/starlark/README.md
>  [dict]: https://github.com/google/starlark-go/blob/master/doc/spec.md#dictionaries
Good catch!

2022-04-06 15:18 UTC, Hipska approved these changes

2022-04-12 13:54 UTC, powersj approved these changes

2022-04-12 13:54 UTC, merged