feat(exec, execd): add an option to pass a custom environment to their child process
influxdata/telegraf pull request #11049
Opened 2022-04-28 15:24 UTC by an-mmx

resolves #9281

adds support for environment variables for **execd** and **exec** plugins

example usage:
```toml
[[inputs.execd]]
  command = [
    "/opt/custom-plugins/my-custom-plugin",
    "-config", "/opt/custom-plugins/my-custom-plugin.conf",
    "-interval", "30s",
  ]
  environment = ["LD_LIBRARY_PATH=/opt/app/lib64"]
```

2022-04-28 18:47 UTC, powersj requested changes
Hi!

This is pretty sweet work! Thank you for putting this all together and with tests.

My only concern is with the sample config in each of the README. I have suggested an update, but feel free to let me know if you think otherwise.

Thanks again!

2022-04-28 18:47 UTC, powersj commented on plugins/inputs/exec/README.md
> +  environment = ["LD_LIBRARY_PATH=/opt/custom/lib64"]
The value in the sample config should be the default and commented out. In this case, we don't want everyone's config exporting that library path.

```suggestion
  ## Array of "key=value" pairs to pass as environment variables
  ## e.g. "KEY=value", "USERNAME=John Doe",
  ## "LD_LIBRARY_PATH=/opt/custom/lib64:/usr/local/libs"
  # environment = []
```

2022-04-28 18:47 UTC, powersj commented on plugins/inputs/execd/README.md
> +  environment = ["LD_LIBRARY_PATH=/opt/custom/lib64"]
```suggestion
  ## Array of "key=value" pairs to pass as environment variables
  ## e.g. "KEY=value", "USERNAME=John Doe",
  ## "LD_LIBRARY_PATH=/opt/custom/lib64:/usr/local/libs"
  # environment = []
```

2022-04-28 18:47 UTC, powersj commented on plugins/outputs/exec/README.md
> +  # environment = ["LD_LIBRARY_PATH=/opt/custom/lib64"]
```suggestion
  ## Array of "key=value" pairs to pass as environment variables
  ## e.g. "KEY=value", "USERNAME=John Doe",
  ## "LD_LIBRARY_PATH=/opt/custom/lib64:/usr/local/libs"
  # environment = []
```

2022-04-28 18:47 UTC, powersj commented on plugins/outputs/execd/README.md
> +  environment = ["LD_LIBRARY_PATH=/opt/custom/lib64"]
```suggestion
  ## Array of "key=value" pairs to pass as environment variables
  ## e.g. "KEY=value", "USERNAME=John Doe",
  ## "LD_LIBRARY_PATH=/opt/custom/lib64:/usr/local/libs"
  # environment = []
```

2022-04-28 19:18 UTC, powersj approved these changes

2022-05-10 21:33 UTC, reimda approved these changes

2022-05-10 21:34 UTC, merged