feat(inputs/kafka_consumer): allow to set default fetch message bytes
influxdata/telegraf pull request #11220
Opened 2022-05-30 18:15 UTC by AlbertasB

### Required for all PRs:

- [X] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

This allows setting number of message bytes to fetch from the broker in each request (default 1MB). Similar to the JVM's `fetch.message.max.bytes`. Might be useful in some cases. I needed it specifically to make telegraf consume messages faster from Kafka cluster.

2022-06-22 21:45 UTC, sspaink approved these changes

2022-06-29 19:14 UTC, srebhan reviewed
Hey @AlbertasB, thanks for the PR! I have two small comments. Can you please take a look?

2022-06-29 19:14 UTC, srebhan commented on plugins/inputs/kafka_consumer/README.md
> +  # fetch_message_bytes = 1048576
Can you please rename to `consumer_fetch_default` as this is what you ultimately use it as such.

2022-06-29 19:14 UTC, srebhan commented on plugins/inputs/kafka_consumer/kafka_consumer.go
> +	FetchMessageBytes      int32           `toml:"fetch_message_bytes"`
How about making this a [`config.Size`](https://github.com/influxdata/telegraf/blob/bd516ae587a27d040b457c593e3d5fa6aaf40269/config/types.go#L15) so you can specify human-readable sizes like `1MB` or `1MiB`?

2022-07-25 12:39 UTC, AlbertasB commented
Hey, thanks for the review and the comments. Somehow I did not get the message :(. I will try to make those changes ASAP. Thanks again :)

2022-07-25 19:06 UTC, reimda requested changes
It's looking great, almost ready to merge. It looks like there's an extra file in the PR that needs to be removed: oryxBuildBinary. Maybe a test file that sneaked in?

2022-07-25 19:43 UTC, AlbertasB commented
Ooops no idea how that got there, nice catch! Removed :)

2022-07-25 21:48 UTC, reimda approved these changes

2022-07-25 21:49 UTC, merged