feat: Allow JSONata based transformations in JSON serializer
influxdata/telegraf pull request #11251
Opened 2022-06-03 13:45 UTC by srebhan

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

replaces #11205

This PR adds a new `json_transformation` option to the JSON serializer. This new option can be used to transform the JSON output using the [JSONata language](https://jsonata.org/) to accommodate for requirements on the receiver side. Additional benefits are the various filtering and processing capabilities of the use language (see README for a few basic examples).

2022-06-07 12:46 UTC, srebhan commented
@reimda so you _approve_ it? :-D

2022-07-12 15:51 UTC, sspaink requested changes
This looks really useful! two minor comments, but I think it looks good.

2022-07-12 15:51 UTC, sspaink commented on go.mod
> +require github.com/blues/jsonata-go v1.5.4
Can you put this in the above require block?

2022-07-12 15:51 UTC, sspaink commented on plugins/serializers/json/json_test.go
> +	s, _ := NewSerializer(0, "", "")
The returned error is ignored throughout the test, think we should check it?

2022-07-21 14:37 UTC, sspaink approved these changes

2022-07-21 16:19 UTC, reimda approved these changes

2022-07-21 16:37 UTC, merged