feat(option)!: add ignore_error_inputs option for inputs
influxdata/telegraf pull request #11304
Opened 2022-06-15 02:58 UTC by observeralone

### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #11289 #10694

### Summary
add ignore_error_inputs option to agent for inputs
If set to true, discard the input plugins that produce the error during initialization.
If set to false, the program will exit when an input plugin has an error occurred during the initialization.
Default: false

2022-06-15 06:59 UTC, observeralone commented
!signed-cla

2022-06-15 07:00 UTC, observeralone commented
> Thanks so much for the pull request! 🤝 ✒️ Just a reminder that the CLA has not yet been signed, and we'll need it before merging. Please [sign the CLA](https://www.influxdata.com/legal/cla/) when you get a chance, then post a comment here saying `!signed-cla`

!signed-cla

2022-06-15 07:45 UTC, Hipska commented
Good idea, but I would like to have this also be configurable per plugin.

For example I accept errors for mqtt_consumer plugin, but not for cpu and disk plugin.

Other agent config options like interval also have this, so should be doable.

2022-06-15 07:59 UTC, Hipska commented
On the other hand, see #10086 where they fix the input in question to let it retry at each interval, that could be done for the plugins in question as well.

2022-06-15 08:09 UTC, observeralone commented
> 

Your ideas belong to individual plugin-level switches, which require more granular control.
At the same time it does not conflict with this PR, because it is a master switch
You never know what other inputs will be coming tomorrow because the Init method crashes Telegraf, a master switch is already effective for most needs

2022-06-15 08:19 UTC, observeralone commented
> On the other hand, see #10086 where they fix the input in question to let it retry at each interval, that could be done for the plugins in question as well.

Good idea, but I don't just want to fix mongodb's init method.
Of course, I'm also following the mongodb init fix, hope you guys can fix it soon.
At the same time, we are also trying to figure out how to solve the problem of mongodb, thank you for your PR

2022-06-15 10:01 UTC, Hipska requested changes
Actually, we don't want to allow ignoring `Init()` errors. However, we could accept this PR if this check is done against the `Start()` return value.

Init is for checking actual configuration errors, Start is for actually connecting to endpoints.

Al the same checks could actually also be done for outputs and processors, so only addressing inputs is doing half of the job.

2022-06-15 10:56 UTC, observeralone commented on agent/agent.go
> +		if err != nil && a.Config.Agent.IgnoreErrorInputs {
> This is what could be done to also allow individual inputs to specify if an error should be ignored or not.

I need to confirm your Demand.
Do you mean that I need to add IgnoreInitError option to the InputConfig as a control?
According to the control logic, I listed a table as a judgment whether to ignore the input
|input.Config.IgnoreInitError|a.Config.Agent.IgnoreErrorInputs| Is Ignore|
|---|---|---|
|true|true|true|
|true|false|true|
|false|true|true|
|false(default)|false(default)|false(default)|

2022-06-15 11:03 UTC, Hipska commented on agent/agent.go
> +		if err != nil && a.Config.Agent.IgnoreErrorInputs {
You got it completely correct!

2022-06-16 08:56 UTC, Hipska requested changes
Simplify the documentation a bit.

2022-06-16 10:57 UTC, observeralone commented
I will close this PR and the new PR address is: https://github.com/influxdata/telegraf/pull/11313

2022-06-16 10:57 UTC, closed without merging