fix: Regression in temps introduced by gopsutil update
influxdata/telegraf pull request #11301
Opened 2022-06-14 12:39 UTC by srebhan

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #11294 

This PR brings back critical (`_crit`) and high (`_max`) temperature levels lost during a gopsutil update. We cannot restore the critical-alarm threshold (`_critalarm`) as this information is not returned anymore.

Furthermore, this PR also introduces a `output_scheme` flag to allow to get the critical, high and actual temperatures as _fields_ in one metric per sensor instead of one metric per sensor and type.

2022-06-14 14:16 UTC, Hipska requested changes

2022-06-14 14:16 UTC, Hipska commented on plugins/inputs/temp/README.md
> +For `output = "measurement" (default) the output will look like this
```suggestion
For `output = "measurement"` (default) the output will look like this
```

2022-06-14 14:16 UTC, Hipska commented on plugins/inputs/temp/README.md
>  ```shell
```suggestion
```text
```

2022-06-14 14:16 UTC, Hipska commented on plugins/inputs/temp/README.md
> +For `output = "field" the output will look like this
```suggestion
For `output = "field"` the output will look like this
```

2022-06-14 14:16 UTC, Hipska commented on plugins/inputs/temp/README.md
> +```shell
This is not a shell script
```suggestion
```text
```

2022-06-14 14:16 UTC, Hipska commented on plugins/inputs/temp/sample.conf
> +  # output_scheme = "measurement"
Maybe add a newline?

2022-06-14 15:37 UTC, Hipska commented on plugins/inputs/temp/temp_nolinux.go
> +		return fmt.Errorf("error getting temperatures info: %s", err)
```suggestion
		if strings.Contains(err.Error(), "not implemented yet") {
			return fmt.Errorf("plugin is not supported on this platform: %w", err)
		}
		return fmt.Errorf("error getting temperatures info: %w", err)
```

2022-09-21 21:59 UTC, powersj commented
@srebhan given the user reported the fields are still missing in #11294, and you filed the upstream issue, should this be closed for now?

2022-09-26 18:58 UTC, srebhan commented
Yeah seems like a good idea to close this PR. However, the upstream issue is sitting there for some time already...

2022-09-26 18:58 UTC, closed without merging