feat: add use regular reads workaround to inputs.opcua
influxdata/telegraf pull request #11630
Opened 2022-08-07 10:07 UTC by R290

# Required for all PRs

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #11559

Added workaround to use regular reads instead of registered reads.

2022-09-13 08:12 UTC, Hipska requested changes

2022-09-13 08:12 UTC, Hipska commented on plugins/inputs/opcua/README.md
> +
```suggestion
## Metrics

Metrics are produced according to the defined node ID and group configuration.

```

2022-09-13 08:12 UTC, Hipska commented on plugins/inputs/opcua/opcua.go
> +		return fmt.Errorf("Read failed: %v", err)
While refactoring, please also use `%w` for errors:
```suggestion
		return fmt.Errorf("Read failed: %w", err)
```

2022-09-13 08:12 UTC, Hipska commented on plugins/inputs/opcua/sample.conf
> +    # use_regular_reads = true
The example conf should represent the default values for commented out parameters:
```suggestion
    # use_regular_reads = false

```

2022-09-14 07:51 UTC, Hipska approved these changes

2022-09-14 07:54 UTC, Hipska commented
Have a look auth the `test-go-linux` check and fix the issues that come from it.
You can also run this on your local machine before pushing, see [Unit Tests](https://github.com/influxdata/telegraf/tree/master/docs/developers#common-development-tasks) section.

2022-09-14 17:51 UTC, R290 commented
Good point on the `make docs`. I accepted your changes from within GitHub, so I didn't run any checks before committing. For some reason `make check` wants me to change 375 files (including opcua.go) using `make fmt`...

2022-09-21 22:29 UTC, powersj commented
@R290 is this one ready to review or was there additional development required? Thanks!

2022-09-26 16:08 UTC, R290 commented
The attached issue contains of 2 parts, and this pull only resolves the second part:
```telegraf needs to handle auto-reconnect and that we should reconsider using registered reads```
For the first part some issues within the underlying opcua library need to be fixed, but this has been eerily quiet for the past six weeks or so. Feel free to review and merge though, the changes are only a small workaround.

2022-09-26 17:30 UTC, powersj approved these changes
Thanks for putting this up. fwiw I think I held off earlier because this was marked draft.

2022-09-26 17:33 UTC, MyaLongmire approved these changes

2022-09-26 17:34 UTC, merged

2022-09-27 15:52 UTC, LarsStegman commented
I know this has already been merged, but it has not yet been released. Might I suggest using `UseUnregisteredReads` as the config name. I think `regular` could be confusing.

2022-09-27 15:55 UTC, MyaLongmire commented
@LarsStegman that's a great idea! Are you willing to put up a pr or should i?

2022-09-27 15:56 UTC, LarsStegman commented
You can do it if you want 🙂

2022-09-27 16:05 UTC, MyaLongmire commented
@LarsStegman pr can be found [here](https://github.com/influxdata/telegraf/pull/11892) :)