refactor: Changes corresponding to new ADX SDK Standards
influxdata/telegraf pull request #11697
Opened 2022-08-17 13:39 UTC by asaharn

# Required for all PRs

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

 Changes as per the new Azure data explorer SDK. Modified test cases accordingly.

2022-08-24 08:25 UTC, asaharn commented
@srebhan  Have raise a new PR. Please take a look and suggest If there are any changes required. 
Note: This is the new PR we have raise as per the discussion on #11587

2022-08-24 13:21 UTC, powersj commented
Hi @asaharn,

Thanks for clarifying. I have closed the old PR and requested @srebhan review this PR. He is currently out, but when he gets back can get around to this.

Thanks!

2022-09-09 06:38 UTC, asaharn commented
Hi @powersj , thanks for update. 

Hi @srebhan , Please have a look whenever you get back and get time. That would be really helpful.

2022-09-14 06:01 UTC, asaharn commented
Hi @srebhan , hoping that you are back from vacations. Let me know if something else is required for the changes.

2022-09-20 11:12 UTC, srebhan requested changes
Thanks @asaharn for the update! I have some smaller comment in the code.

However, I still think that you should more strictly split the changes to the code and the test. Please change `azure_data_explorer.go` as you did (plus my comments) and keep changes to the test to a **bare minimum**. That is, change the mock client stuff but *DO NOT* reorganize the test code or change the way results are checked!
The reorganization of tests can (and should) be done in a separate PR *without* changing the code.

2022-09-20 11:12 UTC, srebhan commented on plugins/outputs/azure_data_explorer/azure_data_explorer.go
> +	return kustoerrors.GetCombinedError(errs...)
Can we please invert this
```suggestion
	if len(errs) > 0 {
		// Combine errors into a single object and return the combined error
		return kustoerrors.GetCombinedError(errs...)
	}
	
	adx.Log.Info("Closed ingestors and client")
	return nil
```
This makes it easier to extend that function later and also eases following the flow.

2022-09-20 11:12 UTC, srebhan commented on plugins/outputs/azure_data_explorer/azure_data_explorer.go
> +	adx.Log.Debugf("Metrics array length %d for table %s", length, tableName)
This is very technical. How about
```suggestion
	adx.Log.Debugf("Writing %s metrics to table %q", length, tableName)
```

2022-09-20 11:12 UTC, srebhan commented on plugins/outputs/azure_data_explorer/azure_data_explorer_test.go
> +	expectedResultMap2 := map[string]string{"test2": `{"fields":{"value":1.0},"name":"test2","tags":{"tag1":"value1"},"timestamp":1257894000}`, "test3": `{"fields":{"value":2.0},"name":"test3","tags":{"
Can we please change the formatting here so it is easier to see what is going on?
```suggestion
	mockClient := kusto.NewMockClient()
	expectedResultMap := map[string]string{
		"test1": `{"fields":{"value":1},"name":"test1","tags":{"tag1":"value1"},"timestamp":1257894000}`},
	}
	mockMetrics := testutil.MockMetrics()
	// Multi tables
	mockMetricsMulti := []telegraf.Metric{
		testutil.TestMetric(1.0, "test2"),
		testutil.TestMetric(2.0, "test3"),
	}
	expectedResultMap2 := map[string]string{
		"test2": `{"fields":{"value":1.0},"name":"test2","tags":{"tag1":"value1"},"timestamp":1257894000}`,
		"test3": `{"fields":{"value":2.0},"name":"test3","tags":{"tag1":"value1"},"timestamp":1257894000}`,
	}
```

2022-09-27 07:54 UTC, asaharn commented
Closing PR, #11874 raised.

2022-09-27 07:54 UTC, closed without merging