feat(sql): AllowConnectionFailures does not cause Telegraf to exit on initial connection failure - disabled by default
influxdata/telegraf pull request #11693
Opened 2022-08-16 22:26 UTC by conorevans

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format

resolves #11457 

If the initial connection fails, we spawn a goroutine to periodically reconnect. I will add README (though I don't think I can add unit tests, maybe that's just a lack of knowledge though). This is an initial implementation so would like to get some feedback before continuing... it seems sound to me but I'm not ultra experienced in Go - to my knowledge once we spawn the goroutine the recursive calls therein should be handled within that same goroutine (i.e. not spawn additional goroutines that need cleaning, and won't block the main program)

2022-08-16 22:27 UTC, conorevans commented
@powersj if you don't mind taking a look, thanks 🙏

2022-08-17 00:14 UTC, conorevans commented on plugins/inputs/sql/sql.go
> +		go s.connect()
Should also return here to not start below (start is called from within connect)

2022-09-13 15:29 UTC, Hipska commented
Could you already fix the linter errors?

2023-02-16 21:54 UTC, powersj commented
@conorevans sorry I never responded on this one. Not sure how I missed this. I started looking at this today, rebased on master to at least get things passing, but it isn't in a working state. I need to sync with Sven on how we want to do this. You certainly have the right idea and I think what we need to work out is how we want to do this in general for these service inputs. 

Part of me thinks each service input may be unique in how it retries (e.g. kafka recently had retries added in a very specific way). On the other hand this could be as simple as a boolean that says to ignore connection errors and retries at each gather cycle.

Let me sync up and get back to looking at this again.

2023-05-16 14:28 UTC, Hipska requested changes

2023-05-16 14:28 UTC, Hipska commented on plugins/inputs/sql/sql.go
> +	maxReconnectInterval = 60 * time.Second
`maxReconnectInterval` can be a constant.

2023-07-07 15:57 UTC, closed without merging