feat(statsd): add support for histogram buckets with timing metrics
influxdata/telegraf pull request #11708
Opened 2022-08-22 14:47 UTC by lahsivjar

# Required for all PRs

- [ ] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #8572

2022-08-22 14:50 UTC, lahsivjar commented
!signed-cla

2022-09-13 14:50 UTC, Hipska requested changes

2022-09-13 14:50 UTC, Hipska commented on plugins/inputs/statsd/statsd.go
> +	HistogramBuckets []Number
Example config and README for this new config option needs to be added.

2022-09-13 14:50 UTC, Hipska commented on plugins/inputs/statsd/statsd_test.go
> +	acc.AssertContainsFieldsWithLeTag(t, "test_timing_bucket", "+Inf", map[string]interface{}{"value": int64(5)})
These custom assert method seem too specific, I think its can be replaced by using `acc.AssertContainsTaggedFields`.

2022-10-05 18:09 UTC, closed without merging