feat: use system wide proxy settings for prometheus input plugin
influxdata/telegraf pull request #11729
Opened 2022-08-26 13:00 UTC by erwiese

resolves #11728

2022-08-26 13:18 UTC, powersj requested changes
Hi,

Thanks for taking the time to put up a PR.

In Telegraf, we already have a standard HTTP client config that allows users to set the proxy as a part of their configuration. It would be good to use the same behavior across plugins.

Take a look at the HTTP plugin in how it [creates a client](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/http/http.go#L57) with the additional `httpconfig.HTTPClientConfig`.

As well, we would to [add the configuration options](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/http/sample.conf#L35-L36) for the proxy to the plugin configuration.

2022-09-02 08:24 UTC, erwiese commented
Hi, could you already review my changes? or anything else missing?

2022-09-07 09:27 UTC, srebhan reviewed
@erwiese, your change looks a lot better this way. Thanks for updating the PR! I have one request left to avoid recreating the `client` over and over. Can you please take a look?

2022-09-07 09:27 UTC, srebhan commented on plugins/inputs/prometheus/prometheus.go
>  	}
Please move this to an `Init() error` function as it isn't really _required_ to recreate the client in every `Gather()` cycle... The `Init()` function is then called automatically by Telegraf after setting all user-configuration-options.

2022-09-09 09:59 UTC, Hipska commented
Shouldn't the unix socket client stuff also be added to Init in this case? It is also making a new client on each interval + URL. Both (http & unix) can be placed in the same `p.client`. Furthermore the `response_timeout` can be deprecated in favour of `timeout`.

2022-09-12 13:30 UTC, powersj approved these changes

2022-09-12 13:42 UTC, Hipska commented
`response_time` could be marked as deprecated and still being used when `timeout` is not set..

2022-09-12 13:51 UTC, Hipska approved these changes

2022-09-13 17:48 UTC, MyaLongmire approved these changes

2022-09-13 17:48 UTC, merged