feat(inputs.directory_monitor): Traverse sub-directories
influxdata/telegraf pull request #11773
Opened 2022-09-06 21:02 UTC by sspaink

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #11718, https://github.com/influxdata/feature-requests/issues/441

This resolves a feature request to have the input plugin `directory_monitor` also process sub-directories. This does change the default behavior, I suppose this could be a breaking change? Not sure if this would be a problem for users? I could add a configuration flag but the best idea I have for this is a boolean flag called "recurse=true/false", so if you think a config option should be required be happy to hear suggestions.

2022-09-07 07:22 UTC, Hipska requested changes
I think this should be a user configurable setting to not change behaviour for current users?

Edit: Your suggested "recurse=true/false"  sounds good to me.

PS: This feature would be a useful for me as well!

2022-09-07 14:52 UTC, Hipska commented on plugins/inputs/directory_monitor/README.md
> +  ## The directory to move finished files to (maintaining directory hierachy from source.
```suggestion
  ## The directory to move finished files to (maintaining directory hierachy from source).
```

2022-09-07 14:52 UTC, Hipska commented on plugins/inputs/directory_monitor/directory_monitor.go
> +			return io.EOF
Not sure, but can this `nolint` be removed because of this change?

2022-09-07 15:23 UTC, Hipska approved these changes

2022-09-07 19:08 UTC, srebhan approved these changes
Looks good to me. Thanks for looking into it @sspaink!

2022-09-07 19:08 UTC, merged

2022-09-08 12:49 UTC, Hipska commented
@sspaink one question, do the options `files_to_monitor` and `files_to_ignore` now work with paths? It doesn't seem so, and now it's not possible to include/exclude certain files..

2022-09-09 07:04 UTC, Hipska commented
Yeah, but the names are the same, so only based on name it isn't possible to distinguish

2022-09-09 17:10 UTC, sspaink commented
@Hipska Good point, I've created a pull request to support paths in the ignore and monitor config options: https://github.com/influxdata/telegraf/pull/11784 could you take a look and maybe try it out to make sure it works for you?