chore(readme): add resource links and logo to readme
influxdata/telegraf pull request #11817
Opened 2022-09-15 18:24 UTC by charlesmahler

updating readme to give some visibility to new learning resources available for new users of Telegraf

- [x] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2022-09-20 17:26 UTC, sspaink requested changes
Thank you for the pull request! So adding HTML to a markdown document isn't best practice, could you update your changes to use markdown syntax only? I realize in order to center align you need to use HTML, but I think not having the centering is acceptable.

2022-09-20 17:26 UTC, sspaink commented on README.md
> +</a>
I recommend we move this to the bottom of the `Getting Started` section otherwise it overshadows the commands that are helpful at a quick glance.

2022-09-20 17:26 UTC, sspaink commented on README.md
> +</div>
Having two logos at the top of the README.md seems a bit much, I prefer we keep the tiger at the top and maybe move the `telegraf` picture elsewhere or remove it. It doesn't look great with a dark theme.

2022-09-23 08:38 UTC, Hipska commented on README.md
> +  </a>
While we are at it, can we change all shields to be in the same theme? (its possibly by using shields.io for all)

2022-10-07 18:09 UTC, closed without merging