chore(deps): Replace go-ping by pro-bing
influxdata/telegraf pull request #11836
Opened 2022-09-19 14:46 UTC by Hipska

# Required for all PRs

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.
- [x] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

The go-ping/ping package is going to be abandoned.

2022-09-19 19:11 UTC, sspaink approved these changes
Thanks for noticing this happened and migrating it to the new repository. Kind of a strange name lol

2022-09-20 08:41 UTC, SuperQ commented
Yea, we're planning to expand it to support other probe types. Like TCP or HTTP. We decided to go with a silly name. :grin:

2022-09-20 08:42 UTC, SuperQ commented on go.mod
> +	github.com/prometheus-community/pro-bing v0.0.0-20220620120154-c0162ab18714
I just tagged v0.1.0 for you. :)

2022-09-20 09:18 UTC, Hipska commented on go.mod
> +	github.com/prometheus-community/pro-bing v0.0.0-20220620120154-c0162ab18714
Oh great, will update..

2022-09-21 19:12 UTC, reimda requested changes

2022-09-21 19:12 UTC, reimda commented on plugins/inputs/ping/ping.go
> +	probing "github.com/prometheus-community/pro-bing"
Let's keep the import name ping. That will cut down on unnecessary changes in the PR

```suggestion
	ping "github.com/prometheus-community/pro-bing"
```

2022-09-21 19:12 UTC, reimda commented on plugins/inputs/ping/ping_test.go
> +	probing "github.com/prometheus-community/pro-bing"
Same here

2022-09-21 19:14 UTC, reimda commented
There is no notice on go-ping/ping that says it's abandoned. I see that prometheus-community/pro-bing has recent activity and I appreciate the work people are doing there. Can you share some background on why we should switch to the fork?

2022-09-21 19:24 UTC, Hipska commented
In  their Slack Channel @SuperQ opted to archive it or at least mention it on the readme, but none of the maintainers responded to that. It is so abandoned that they even not care to inform the users 😉

2022-09-21 20:50 UTC, SuperQ commented
Yea, that's how difficult it is. Due to the dual approval necessary, I can't open a PR to even say that it's abandoned.

If either of you could open a PR to update the README, I could try and get it merged eventually.

2022-09-26 19:04 UTC, merged

2022-09-27 20:27 UTC, reimda commented
And thanks @SuperQ for keeping the ping project alive with pro-bing

2022-12-23 11:23 UTC, Hipska commented
@SuperQ do you have something in mind?
> If either of you could open a PR to update the README, I could try and get it merged eventually.