fix: fixing null delimiters in csv, change the selected bytes before …
influxdata/telegraf pull request #12247
Opened 2022-11-16 09:16 UTC by Meceron

[https://github.com/influxdata/telegraf/issues/12243](url)

…parsing to pipeline

# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

2022-11-16 14:59 UTC, powersj commented
Hi,

Thanks for putting up this PR. It appears that this is essentially a "find and replace" before doing any parsing. Instead of having this hard-code the replacement, can we instead rename `csv_force_replace_delimiter` to `csv_delimiter_replace` and use the `csv_delimiter` as the replacement?

Essentially if I had:

```
csv_delimiter = ","
csv_delimiter_replace = "\u0000"
```

It would replace those null bytes with commas.

What do you think about that? Before you go off and make changes I would like to hear from @srebhan as well

2022-11-16 15:54 UTC, srebhan commented
@Meceron thanks for your PR! Instead of forcing the user to give another option how about the following (in pseudo-code):

1. Check if delimiter is valid, i.e. copy the [validDelim function of encoding/csv](https://cs.opensource.google/go/go/+/refs/tags/go1.19.3:src/encoding/csv/reader.go;l=95)
2. If invalid:
2.1 replace all comma (`, ) with `\ufffd` which is the unicode replacement character and should not appear in the text
2.2 replace all user-specified delimiter instances by comma
2.3 change CSV delimiter to comma
2.4 set a flag that we replaced data e.g. `p.delimiterReplaced = true`
3. do the csv parsing
4. If `p.delimiterReplaced == true` replace `\ufffd`  in _all_ resulting fields back to comma

What do you think?

2022-11-17 10:17 UTC, Meceron commented
Thanks for the advice! I've changed code.

2022-11-17 19:40 UTC, powersj reviewed
Thanks for the quick turn around! I have put up some comments that clarify the docs and rename the bool to `invalidDelimiter`.

Take a look and let us know!

2022-11-17 19:40 UTC, powersj commented on plugins/parsers/csv/README.md
> +  ## in the data the blacklisted delimiters will be changed to comma, and original commas will be changed to "\ufffd"
What about:

```suggestion
  ## Please note that if you use invalid delimiters (e.g. "\u0000"), commas
  ## will be changed to "\ufffd", the invalid delimiters changed to a comma
  ## during parsing, and afterwards the invalid characters and commas are
  ## returned to their original values.
```

2022-11-17 19:40 UTC, powersj commented on plugins/parsers/csv/parser.go
> +	}
```suggestion
	// If using an invalid delimiter, replace commas with replacement and
	// invalid delimiter with commas
	if p.invalidDelimiter {
		buf = bytes.Replace(buf, []byte(commaByte), []byte(replacementByte), -1)
		buf = bytes.Replace(buf, []byte(p.Delimiter), []byte(commaByte), -1)
	}
```

2022-11-17 19:40 UTC, powersj commented on plugins/parsers/csv/parser.go
> +	// if the delimiter is balckited by the go reader
```suggestion
	// Check if delimiter is invalid
```

2022-11-17 19:40 UTC, powersj commented on plugins/parsers/csv/parser.go
> +	delimiterReplaced bool
```suggestion
	invalidDelimiter bool
```

2022-11-17 19:40 UTC, powersj commented on plugins/parsers/csv/parser.go
> +		p.delimiterReplaced = !validDelim(runeStr[0])
```suggestion
		p.invalidDelimiter = !validDelim(runeStr[0])
```

2022-11-17 19:40 UTC, powersj commented on plugins/parsers/csv/parser.go
> +	if !p.delimiterReplaced && p.Delimiter != "" {
```suggestion
	if !p.invalidDelimiter && p.Delimiter != "" {
```

2022-11-17 19:40 UTC, powersj commented on plugins/parsers/csv/parser.go
> +	if p.delimiterReplaced {
```suggestion
	if p.invalidDelimiter {
```

2022-12-08 14:52 UTC, srebhan commented
@Meceron any news on this PR?

2022-12-08 15:07 UTC, Hipska requested changes
Whoops, I didn't finished my review..

2022-12-09 16:03 UTC, Meceron commented
Sorry , I was on sickleave :(. As I see You All done everything, thank you!

2022-12-09 16:04 UTC, srebhan reviewed
I only do have two small comments @Meceron. Can you please address those and consider the other comment of @Hipska!?

2022-12-09 16:04 UTC, srebhan commented on plugins/parsers/csv/parser.go
> +var commaByte = "\u002C"
Can you please make this
```suggestion
const replacementByte = "\ufffd"
const commaByte = "\u002C"
```

2022-12-09 16:04 UTC, srebhan commented on plugins/parsers/csv/parser.go
> +
Please attribute the code here
```suggestion
// Taken from upstream Golang code see
// https://github.com/golang/go/blob/release-branch.go1.19/src/encoding/csv/reader.go#L95
func validDelim(r rune) bool {
	return r != 0 && r != '"' && r != '\r' && r != '\n' && utf8.ValidRune(r) && r != utf8.RuneError
}

```

2022-12-12 15:28 UTC, powersj commented
I wanted to try to land this for today's release, so I accepted the changes.

2022-12-12 16:04 UTC, Hipska commented
@powersj my comments are still open and un-addressed..

2022-12-12 16:37 UTC, srebhan commented
@Meceron can you please at least make those two strings const?

2022-12-12 16:40 UTC, powersj commented on plugins/parsers/csv/parser_test.go
> +	testCSV := strings.Join([]string{"3.4", "70", "test_name"}, "\u0000")
I prefer the existing as it makes it very clear what is going on versus having to count and determine the end of a unicode value

2022-12-12 16:40 UTC, Hipska commented
@srebhan This is what @powersj already did in a315d23.

2022-12-12 16:41 UTC, powersj commented
> @Meceron can you please at least make those two strings const?

This was done already. I accepted your change that did this.

2022-12-12 16:51 UTC, srebhan approved these changes
Thanks for the nice improvement @Meceron! LGTM.

2022-12-12 16:55 UTC, powersj commented
Merging as integration test is a known issue fixed on master

2022-12-12 16:55 UTC, merged