chore: update package repo GPG key
influxdata/telegraf pull request #12544
Opened 2023-01-24 20:06 UTC by powersj

fixes: #12542

2023-01-24 20:21 UTC, jdstrand requested changes
Thanks for doing this. Couple little things inline.

2023-01-24 20:21 UTC, jdstrand commented on README.md
> +echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-oss-archive_compat.key' | sha256sum -c && cat influxdb.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxda
The `&& cat influxdb.key` should be `&& cat influxdata-oss-archive_compat.key`

The `| sudo tee /etc/apt/trusted.gpg.d/influxdata-oss-archive_compat.key` should be `| sudo tee /etc/apt/trusted.gpg.d/influxdata-oss-archive_compat.gpg`

2023-01-24 20:21 UTC, jdstrand commented on README.md
> +echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-oss-archive_compat.key] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list
`/etc/apt/trusted.gpg.d/influxdata-oss-archive_compat.key` should be `/etc/apt/trusted.gpg.d/influxdata-oss-archive_compat.gpg`

2023-01-24 20:43 UTC, jdstrand approved these changes

2023-01-25 14:46 UTC, jdstrand approved these changes

2023-01-26 09:54 UTC, srebhan approved these changes

2023-01-26 09:55 UTC, merged