feat(inputs.disk): add label as tag
influxdata/telegraf pull request #12696
Opened 2023-02-16 19:22 UTC by powersj

fixes: #12594

2023-02-21 10:14 UTC, Hipska requested changes
Please also update the README sections Metrics and Example Output.

2023-02-22 08:55 UTC, Hipska approved these changes

2023-02-22 10:41 UTC, srebhan reviewed
@powersj one small suggestion... Can you please take a look!?

2023-02-22 10:41 UTC, srebhan commented on plugins/inputs/disk/disk.go
> +		}
Wouldn't this be more clear
```suggestion
		label, err := disk.Label(strings.TrimPrefix(device, "/dev/"))
		if err == nil && label != "" {
			tags["label"] = label
		}
```

2023-02-22 14:12 UTC, powersj commented on plugins/inputs/disk/disk.go
> +		}
agreed, committed

2023-02-22 14:15 UTC, Hipska approved these changes

2023-02-22 14:55 UTC, merged