chore: Fix linter findings for errorlint (part1)
influxdata/telegraf pull request #12701
Opened 2023-02-17 18:27 UTC by zak-pawel

Address findings for [errorlint](https://github.com/polyfloyd/go-errorlint) - finds code that can cause problems with the error wrapping scheme introduced in Go 1.13.

It is only part of the bigger job.
After all findings in whole project are handled, we can enable `errorlint` linter to guard this.

Following findings in `agent`, `cmd`, `config`, `internal`, `models`, `testutil` and `tools` packages were fixed:
```
agent/agent.go:200:22                             errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
agent/agent.go:207:26                             errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
agent/agent.go:214:27                             errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
agent/agent.go:221:26                             errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
agent/agent.go:228:23                             errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
cmd/telegraf/main.go:199:36                       errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
cmd/telegraf/telegraf.go:155:20                   errorlint  comparing with != will fail on wrapped errors. Use errors.Is to check for a specific error
cmd/telegraf/telegraf.go:156:60                   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/config.go:476:47                           errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/config.go:487:69                           errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/config.go:617:62                           errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/config.go:635:62                           errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/config.go:651:53                           errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/config.go:729:101                          errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/config.go:874:69                           errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/config.go:880:56                           errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/deprecation.go:38:75                       errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/deprecation.go:45:82                       errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/deprecation.go:119:48                      errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/deprecation.go:151:71                      errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/secret.go:110:58                           errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/secret.go:130:56                           errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
config/secret.go:182:51                           errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
internal/content_coding.go:64:5                   errorlint  comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error
internal/content_coding.go:228:19                 errorlint  comparing with != will fail on wrapped errors. Use errors.Is to check for a specific error
internal/content_coding.go:259:19                 errorlint  comparing with != will fail on wrapped errors. Use errors.Is to check for a specific error
internal/http.go:138:16                           errorlint  type assertion on error will fail on wrapped errors. Use errors.As to check for specific errors
internal/internal.go:187:20                       errorlint  type assertion on error will fail on wrapped errors. Use errors.As to check for specific errors
internal/process/process.go:116:51                errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
internal/snmp/translate.go:138:69                 errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
models/filter.go:57:55                            errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
models/filter.go:61:55                            errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
models/filter.go:66:56                            errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
models/filter.go:70:56                            errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
models/filter.go:75:57                            errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
models/filter.go:79:57                            errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
models/filter.go:85:55                            errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
models/filter.go:91:55                            errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
testutil/container.go:66:54                       errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
testutil/container.go:76:48                       errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
testutil/container.go:84:47                       errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
testutil/container.go:113:56                      errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
testutil/file.go:81:79                            errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
testutil/file.go:107:76                           errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
tools/custom_builder/config.go:98:52              errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
tools/custom_builder/config.go:102:68             errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
tools/package_lxd_test/container.go:35:53         errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
tools/package_lxd_test/container.go:40:54         errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
tools/package_lxd_test/container.go:48:53         errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
tools/package_lxd_test/lxd.go:156:50              errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
tools/readme_config_includer/generator.go:81:63   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
tools/readme_config_includer/generator.go:87:65   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
tools/update_goversion/main.go:75:7               errorlint  comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error
```

2023-02-17 20:09 UTC, powersj approved these changes

2023-02-21 09:15 UTC, Hipska requested changes
Many thanks, it would be great if we can enable this linter, I can't recall how many times I asked to change `%v` to `%w` on PRs.

Shouldn't we also be consistent to always use `:` before the error? I see sometimes `,` is used..

2023-02-21 09:15 UTC, Hipska commented on cmd/telegraf/main.go
> +				return fmt.Errorf("%w and %s", err, err2)
`err2` isn't found by this linter?
```suggestion
				return fmt.Errorf("%w and %w", err, err2)
```

2023-02-21 09:15 UTC, Hipska commented on config/config.go
> +				return nil, fmt.Errorf("retry %d of %d failed connecting to HTTP config server %w", i, retries, err), false
```suggestion
				return nil, fmt.Errorf("retry %d of %d failed connecting to HTTP config server: %w", i, retries, err), false
```

2023-02-21 09:15 UTC, Hipska commented on testutil/container.go
> +			return fmt.Errorf("failed to find '%s' - %w", port, err)
```suggestion
			return fmt.Errorf("failed to find %q: %w", port, err)
```

2023-02-22 10:55 UTC, srebhan commented
@Hipska I would appreciate a consistent error formatting, but I think this is beyond the scope of this PR. However, additional PRs are welcome!

2023-02-22 10:59 UTC, srebhan reviewed
@zak-pawel thanks for the epic effort. I'd love to see this linter enabled! However, I agree with the comments of @Hipska. Can you please fix those!?

2023-02-22 10:59 UTC, srebhan commented on cmd/telegraf/main.go
> +				return fmt.Errorf("%w and %s", err, err2)
Valid point.

2023-02-22 10:59 UTC, srebhan commented on testutil/container.go
> +			return fmt.Errorf("failed to find '%s' - %w", port, err)
Agree here.

2023-02-22 11:05 UTC, Hipska commented
@srebhan during yesterdays maintainers meeting we agreed the uniform error messages with `:`, but there is no way to enforce it with linters. I think @zak-pawel would update the PRs to change all using `, %w` to use `: %w`.

2023-02-22 11:19 UTC, zak-pawel commented on cmd/telegraf/main.go
> +				return fmt.Errorf("%w and %s", err, err2)
Done

2023-02-22 11:20 UTC, zak-pawel commented on config/config.go
> +				return nil, fmt.Errorf("retry %d of %d failed connecting to HTTP config server %w", i, retries, err), false
Changed

2023-02-22 11:20 UTC, zak-pawel commented on testutil/container.go
> +			return fmt.Errorf("failed to find '%s' - %w", port, err)
Done

2023-02-22 11:21 UTC, Hipska requested changes
Almost ;-)

2023-02-22 11:21 UTC, Hipska commented on testutil/container.go
> +			return fmt.Errorf("failed to find %q - %w", port, err)
```suggestion
			return fmt.Errorf("failed to find %q: %w", port, err)
```

2023-02-22 11:23 UTC, Hipska commented on testutil/container.go
> +			return fmt.Errorf("failed to find '%s' - %w", port, err)
Almost done, see new review.

2023-02-22 11:25 UTC, zak-pawel commented on testutil/container.go
> +			return fmt.Errorf("failed to find %q - %w", port, err)
Done already, refresh code :)

2023-02-22 11:27 UTC, Hipska approved these changes

2023-02-22 11:27 UTC, Hipska commented on testutil/container.go
> +			return fmt.Errorf("failed to find %q - %w", port, err)
Strange 🤔

2023-02-22 11:57 UTC, srebhan approved these changes
Nice. Thanks again @zak-pawel for this epic effort!

2023-02-22 11:57 UTC, merged