chore: Fix linter findings for errorlint (part2)
influxdata/telegraf pull request #12702
Opened 2023-02-17 19:50 UTC by zak-pawel

Address findings for [errorlint](https://github.com/polyfloyd/go-errorlint) - finds code that can cause problems with the error wrapping scheme introduced in Go 1.13.

It is only part of the bigger job.
After all findings in whole project are handled, we can enable `errorlint` linter to guard this.

Following findings in `plugins/aggregators`, `plugins/common`, `plugins/parsers`, `plugins/processors`, `plugins/secretstores` and `plugins/serializers` packages were fixed:
```
plugins/aggregators/quantile/quantile.go:118:72                             errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/encoding/decoder_reader.go:136:64                            errorlint  comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error
plugins/common/encoding/decoder_reader.go:148:9                             errorlint  comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error
plugins/common/encoding/decoder_reader.go:151:9                             errorlint  comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error
plugins/common/encoding/decoder_reader.go:157:24                            errorlint  comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error
plugins/common/jolokia2/client.go:163:60                                    errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/client.go:187:56                                       errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:50:67                                    errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:59:69                                    errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:90:65                                    errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:95:76                                    errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:98:73                                    errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:101:63                                   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:106:75                                   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:110:59                                   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:113:72                                   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:116:62                                   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:140:70                                   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:285:56                                   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:307:71                                   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/opcua/opcua_util.go:313:71                                   errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/shim/goshim.go:113:57                                        errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/shim/goshim.go:118:53                                        errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/shim/input.go:20:50                                          errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/shim/input.go:41:51                                          errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/shim/output.go:17:50                                         errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/shim/processor.go:27:50                                      errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/shim/processor.go:58:7                                       errorlint  comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error
plugins/common/shim/processor.go:61:33                                      errorlint  type assertion on error will fail on wrapped errors. Use errors.As to check for specific errors
plugins/common/starlark/builtins.go:104:56                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/builtins.go:117:56                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/builtins.go:124:56                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/builtins.go:136:56                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/builtins.go:149:56                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/builtins.go:152:56                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/builtins.go:165:56                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/builtins.go:171:56                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/builtins.go:176:57                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/builtins.go:262:56                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/builtins.go:275:56                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/builtins.go:289:56                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/logging.go:32:56                                    errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/starlark.go:111:60                                  errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/starlark/starlark.go:141:20                                  errorlint  type assertion on error will fail on wrapped errors. Use errors.As to check for specific errors
plugins/common/tls/config.go:152:90                                         errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/tls/config.go:161:64                                         errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/tls/config.go:175:64                                         errorlint  non-wrapping format verb for fmt.Errorf. Use `%w` to format errors
plugins/common/tls/config.go:200:52                                         errorlint  non-wrapping forma [...]

2023-02-17 20:08 UTC, powersj approved these changes

2023-02-21 09:45 UTC, Hipska requested changes

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/csv/parser.go
> +						return nil, fmt.Errorf("column type: parse int error %w", err)
```suggestion
						return nil, fmt.Errorf("column type: parse int error: %w", err)
```

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/csv/parser.go
> +						return nil, fmt.Errorf("column type: parse float error %w", err)
```suggestion
						return nil, fmt.Errorf("column type: parse float error: %w", err)
```

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/csv/parser.go
> +						return nil, fmt.Errorf("column type: parse bool error %w", err)
```suggestion
						return nil, fmt.Errorf("column type: parse bool error: %w", err)
```

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/graphite/parser.go
> +		return nil, fmt.Errorf(`field "%s" value: %w`, fields[0], err)
```suggestion
		return nil, fmt.Errorf("field %q value: %w", fields[0], err)
```

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/graphite/parser.go
> +			return nil, fmt.Errorf(`field "%s" time: %w`, fields[0], err)
```suggestion
			return nil, fmt.Errorf("field %q time: %w", fields[0], err)
```

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/json_v2/parser.go
> +				return nil, fmt.Errorf("unable to convert field '%s' to type bool", name)
```suggestion
				return nil, fmt.Errorf("unable to convert field %q to type bool", name)
```

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/json_v2/parser.go
> +				return nil, fmt.Errorf("unable to convert field '%s' to type bool: %w", name, err)
```suggestion
				return nil, fmt.Errorf("unable to convert field %q to type bool: %w", name, err)
```

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/json_v2/parser.go
> +				return nil, fmt.Errorf("unable to convert field '%s' to type float: %w", name, err)
```suggestion
				return nil, fmt.Errorf("unable to convert field %q to type float: %w", name, err)
```

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/json_v2/parser.go
> +				return nil, fmt.Errorf("unable to convert field '%s' to type int: %w", name, err)
```suggestion
				return nil, fmt.Errorf("unable to convert field %q to type int: %w", name, err)
```

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/json_v2/parser.go
> +				return nil, fmt.Errorf("unable to convert field '%s' to type uint: %w", name, err)
```suggestion
				return nil, fmt.Errorf("unable to convert field %q to type uint: %w", name, err)
```

Honestly, I think just `%s` would be sufficient as well for these..

2023-02-21 09:45 UTC, Hipska commented on plugins/processors/topk/topk.go
> +			return "", fmt.Errorf("could not compile pattern: %v %w", t.GroupBy, err)
```suggestion
			return "", fmt.Errorf("could not compile pattern %q: %w", t.GroupBy, err)
```

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/dropwizard/parser.go
> +			return time.Time{}, fmt.Errorf("time %s cannot be parsed with format %s, %w", timeString, timeFormat, err)
See https://github.com/influxdata/telegraf/pull/12701#pullrequestreview-1306991322

2023-02-21 09:45 UTC, Hipska commented on plugins/parsers/dropwizard/parser.go
> +		err = fmt.Errorf("unable to parse dropwizard metric registry from JSON document, %w", err)
See https://github.com/influxdata/telegraf/pull/12701#pullrequestreview-1306991322

2023-02-22 11:08 UTC, srebhan approved these changes
While I agree with @Hipska's comments to unify error messaging format and use `%q`, I also think this is beyond the present PR. Therefor, I do approve and merge the PR. A checker for `%q` would be awesome for the next linter round. ;-)

2023-02-22 11:08 UTC, srebhan commented on plugins/parsers/influx/influx_upstream/parser_test.go
> +					if errors.Is(err, ErrEOF) {
You could make use of `require.ErrorIs` here (see https://pkg.go.dev/github.com/stretchr/testify/require#ErrorIs), but I don't want to hold up this PR for that small improvement.

2023-02-22 11:08 UTC, merged

2023-02-22 11:17 UTC, Hipska commented
There were also other instances where a `:` was missing which @zak-pawel agreed to update in the PR..