feat(processors.converter): convert tag or field as metric timestamp
influxdata/telegraf pull request #12767
Opened 2023-02-28 20:03 UTC by powersj

This adds the timestamp and timestamp_format options to the converter processor. This allows users to take a tag or field and make it the metric timestamp. It uses the same format parsing code that is used throughout Telegraf.

fixes: #12746

2023-03-02 15:47 UTC, Hipska requested changes

2023-03-02 15:47 UTC, Hipska commented on plugins/processors/converter/converter.go
> +	Timestamp       string   `toml:"timestamp"`
I would still use an array for uniformity and as its also done like this for the `measurement` name.

```suggestion
	Timestamp       []string `toml:"timestamp"`
```

2023-03-02 15:47 UTC, Hipska commented on plugins/processors/converter/sample.conf
> +    # timestmap = ""
```suggestion
    float = []
    timestamp = []
```

2023-03-02 15:47 UTC, Hipska commented on plugins/processors/converter/sample.conf
> +    # timestmap = ""
```suggestion
    float = []
    timestamp = []
```

2023-03-09 15:17 UTC, Hipska approved these changes

2023-03-09 16:42 UTC, srebhan approved these changes
Looks good to me. Thanks for taking care of this @powersj!

2023-03-09 16:43 UTC, merged