feat(parsers.influx): Allow a user to set the timestamp precision
influxdata/telegraf pull request #13419
Opened 2023-06-09 17:22 UTC by powersj

fixes: #13407

2023-06-10 05:18 UTC, Hipska commented
This is nice to have, but it does not fix the specific request in #13407

2023-06-25 08:39 UTC, eth5201314 commented
I noticed that your license is unclear. Can you provide more information about how your code can be used?

2023-07-12 08:47 UTC, srebhan reviewed
Just one small comment...

2023-07-12 08:47 UTC, srebhan commented on plugins/inputs/influxdb_v2_listener/influxdb_v2_listener.go
> +					h.Log.Debugf("Error setting precision of parser: %v", err.Error())
```suggestion
					h.Log.Debugf("Error setting precision of parser: %v", err)
```

2023-07-12 08:47 UTC, srebhan commented
@eth5201314 I'm not exactly sure what you are asking... Is your question related to Telegraf as a whole?

2023-07-12 11:12 UTC, Hipska requested changes

2023-07-12 11:12 UTC, Hipska commented on plugins/parsers/influx/influx_upstream/parser_test.go
> +		require.Error(t, parser.Init())
```suggestion
		require.ErrorContains(t, parser.Init(), "invalid time precision")
```

2023-07-12 11:12 UTC, Hipska commented on plugins/parsers/influx/parser_test.go
> +		require.Error(t, parser.Init())
```suggestion
		require.ErrorContains(t, parser.Init(), "invalid time precision")
```

2023-07-12 14:22 UTC, powersj commented on plugins/parsers/influx/parser_test.go
> +	"fmt"
```suggestion
```

2023-07-12 15:34 UTC, srebhan commented on plugins/parsers/influx/parser.go
> +
I think the issue is that the original influx parser is code-generated and therefore we cannot simply add/modify the function. I'm fine with the second instance...

2023-07-12 21:36 UTC, Hipska commented on plugins/parsers/influx/parser.go
> +
But why not align them to look the same?

2023-07-12 21:39 UTC, Hipska approved these changes

2023-07-12 21:40 UTC, Hipska commented
Let's check after a new nightly build? I don't like that warning of file size change 😛

2023-07-13 17:09 UTC, merged