docs: correct wrong sql command
influxdata/telegraf pull request #13934
Opened 2023-09-18 08:54 UTC by schmidt-software

add missing column "day" in sql statement in readme

# Required for all PRs

- [x] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #

2023-09-27 19:37 UTC, powersj commented
@schmidt-software,

Thanks for the PR. I would like to point to documentation in our docs that states the day field is required as a part of this. Thanks again!

2023-10-11 07:06 UTC, Hipska commented
> Are you sure the `day` field is **required** for the database? If so, can you please link to a documentation?!

It was already referenced as the part of the primary key and also for the partitioning, so I think it was a typo to not include it in the schema.

> Furthermore, you should use spaces instead of tabs for indentation as reported by the linter...

Second that..

2023-10-11 08:49 UTC, Hipska requested changes

2023-10-11 08:49 UTC, Hipska commented on plugins/outputs/cratedb/README.md
> +	PRIMARY KEY ("timestamp", "hash_id","day")
```suggestion
  "hash_id" LONG INDEX OFF,
  "timestamp" TIMESTAMP,
  "name" STRING,
  "tags" OBJECT(DYNAMIC),
  "fields" OBJECT(DYNAMIC),
  "day" TIMESTAMP GENERATED ALWAYS AS date_trunc('day', "timestamp"),
  PRIMARY KEY ("timestamp", "hash_id","day")
```

2023-10-26 08:01 UTC, Hipska commented
@srebhan could you apply my suggestion? I think we are then OK to merge?

2023-10-26 13:54 UTC, Hipska approved these changes

2023-10-30 08:01 UTC, srebhan approved these changes
Thanks for the corrections and explanation @Hipska and thanks for the original fix @schmidt-software!

2023-10-30 08:02 UTC, merged