feat(processors.dedup): Add state persistence between runs
influxdata/telegraf pull request #14065
Opened 2023-10-06 21:48 UTC by gazpachoking

# Required for all PRs

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [ ] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary)

resolves #14059

This adds the state persistence interface to the processors.dedup plugin. It's implemented by using the influx serializer/parser to store the metrics.

Turns out there was a bug that non-streaming processors couldn't have state persistence, also fixed that issue in here to make it work.

2023-10-09 12:12 UTC, srebhan approved these changes
Very nice addition @gazpachoking! Thanks for sharing!

2023-10-11 07:57 UTC, Hipska requested changes
@srebhan should a `StatefulPlugin` have tests on their `GetState` and `SetState` methods?

2023-10-11 07:57 UTC, Hipska commented on agent/agent.go
> +	"github.com/influxdata/telegraf/plugins/processors"
Move this line to the block below with the other telegraf imports

2023-10-11 07:57 UTC, Hipska commented on plugins/processors/dedup/dedup.go
> +	influxSerializer "github.com/influxdata/telegraf/plugins/serializers/influx"
Same here, keep telegraf imports together.

Maybe also rename the first one to `influxParser` to have no confusion at all in the code?

2023-10-11 08:01 UTC, Hipska commented on plugins/processors/dedup/dedup.go
> +	}
Is this copy needed?

2023-10-11 08:02 UTC, Hipska commented
@gazpachoking Is there really a need to serialise and unserialise the metrics? Can't you just return `d.Cache`?

2023-10-11 08:26 UTC, srebhan commented
@Hipska it's really better to serialize the metrics as the persister will JSON-serialize the returned state... :-/

2023-10-11 08:29 UTC, Hipska commented
Indeed, and now it will make a JSON string of the serialised metric. So first parse the JSON and then parse the metric. I don't see the benefit here?

2023-10-11 08:31 UTC, srebhan commented
@Hipska the benefit is that the metric is serialized. :-P If you pass a metric to the JSON serializer it will do nothing as the fields are not exported...

2023-10-11 08:35 UTC, Hipska commented
Oh, then maybe that (make metrics JSON serialisable) should be done then?

2023-10-11 08:46 UTC, srebhan commented
@Hipska why? You are losing information in serializing to JSON e.g. if a number is an integer or a float. What is better if we serialize to JSON than if we serialize to line-protocol?

2023-10-11 12:47 UTC, gazpachoking commented
> the benefit is that the metric is serialized. :-P If you pass a metric to the JSON serializer it will do nothing as the fields are not exported...

Yeah, I tried just returning `d.Cache` first, and was just getting an empty JSON object out. I couldn't figure out how to make Go JSON serialize the metric, (and didn't even think of the int vs float issue,) so I went with one of the existing ways to serialize metrics.

2023-10-12 21:07 UTC, merged