docs: Fixing typos
influxdata/telegraf pull request #14359
Opened 2023-11-27 22:11 UTC by deining

This PR fixes various typos I spotted inside the project.

2023-11-28 15:21 UTC, srebhan commented
@deining can you please run `make docs` and fix the merge conflict!?!

2023-11-28 15:36 UTC, Hipska requested changes

2023-11-28 15:36 UTC, Hipska commented on plugins/inputs/jenkins/sample.conf
> +  ## labal contains a comma it is replaced with an underscore.
```suggestion
  ## label contains a comma it is replaced with an underscore.
```

2023-11-28 20:52 UTC, powersj approved these changes
Thanks! I've rebased, made one change, and run make docs.

2023-11-29 13:47 UTC, srebhan approved these changes
Thanks a lot for the fixes @deining! I do agree with Josh that we should ignore the readme linter for this PR...

2023-11-29 13:47 UTC, merged

2023-11-30 14:03 UTC, Hr0bar commented
The fireboard plugin actually does 'return "Celcius"' as a value, so showing the correct spelling in docs is misleading. Would need to be fixed in the return statement too, in which case its a breaking change.