fix: correctly change variable name to `msg_headers_as_tags` from `msg_headers_to_tags`
influxdata/telegraf pull request #14679
Opened 2024-02-04 08:16 UTC by nobel6018

## Summary

Correctly change Kafka telegraf's configuration variable name to `msg_headers_to_tags` from `msg_headers_to_tags`

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #
[x](url) https://github.com/influxdata/telegraf/issues/14678

2024-02-04 08:24 UTC, nobel6018 commented
!signed-cla

2024-02-04 08:24 UTC, nobel6018 commented
`!signed-cla`

2024-02-04 08:26 UTC, nobel6018 commented
!signed-cla

2024-02-05 13:59 UTC, powersj approved these changes

2024-02-05 20:12 UTC, srebhan requested changes
Thanks for the fix @nobel6018 but I think you also need to update `sample.conf` and run `make docs`!

2024-02-06 02:01 UTC, nobel6018 commented
> Thanks for the fix @nobel6018 but I think you also need to update `sample.conf` and run `make docs`!

Thank you for your comment. @srebhan 
- I updated `sample.conf` and pushed it
- I'll run `make docs`

2024-02-06 20:38 UTC, srebhan approved these changes
Thanks a lot @nobel6018!

2024-02-06 20:39 UTC, merged