docs(aggregators.final): Swap useful statements
influxdata/telegraf pull request #15159
Opened 2024-04-15 15:44 UTC by powersj

## Summary
The statements seem switched around currently and are causing confusion for users. Periodic is used to avoid gaps in the data, while timeout is used to only show the last value when a whole bunch come in, i.e. downsample.

## Checklist

- [x] No AI generated code was used in this PR

2024-04-15 16:01 UTC, Hipska approved these changes

2024-04-16 09:43 UTC, srebhan requested changes
I don't think the new wording is correct. On`timeout` all metrics received _within_ the timeout are swallow and the aggregator only outputs the last metric if it is **older** than the timeout! So it "fills a gap" if no metric arrived within timeout.

For downsampling you want to get the data in a _fixed_ interval (usually with a lower frequency than the input). This is exactly what the `periodic` strategy does, it outputs the last metric received at a _fixed interval_ (the `period`). Here the "age" of the metric is irrelevant.

2024-04-16 09:53 UTC, Hipska commented
See [this post](https://community.influxdata.com/t/get-at-least-every-5-min-datapoint-by-mqtt-consumer/33911) for reference how we came to this conclusion. In the use-case of the TS, the current wording is very confusing.

2024-04-16 13:54 UTC, powersj commented
> So it "fills a gap" if no metric arrived within timeout.

This sentence is what is causing confusion. If no metrics are received within a timeout, then nothing is returned. i.e. if no metrics, a gap is produced. The text literally says to use "timeout" to fill gaps, but that is not the behavior.

For example, given the following config, and if I send a single metric:

```toml
[[aggregators.final]]
  period = "10s"
  delay = "5s"
  output_strategy = "timeout"
```

```s
2024-04-16T13:53:00Z D! [aggregators.final] Updated aggregation range [2024-04-16 07:53:00 -0600 MDT, 2024-04-16 07:53:10 -0600 MDT]
metric,topic=telegraf/test value=43 1713275576116715552
2024-04-16T13:53:02Z D! [outputs.file] Wrote batch of 1 metrics in 51.7µs
2024-04-16T13:53:02Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2024-04-16T13:53:10Z D! [aggregators.final] Updated aggregation range [2024-04-16 07:53:10 -0600 MDT, 2024-04-16 07:53:20 -0600 MDT]
2024-04-16T13:53:12Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2024-04-16T13:53:20Z D! [aggregators.final] Updated aggregation range [2024-04-16 07:53:20 -0600 MDT, 2024-04-16 07:53:30 -0600 MDT]
2024-04-16T13:53:22Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2024-04-16T13:53:30Z D! [aggregators.final] Updated aggregation range [2024-04-16 07:53:30 -0600 MDT, 2024-04-16 07:53:40 -0600 MDT]
2024-04-16T13:53:32Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
```

2024-04-16 14:02 UTC, srebhan commented
@powersj I agree that this can cause confusion, but the statement of this PR
```toml
  ##   timeout  -- output a metric if no new input arrived for `series_timeout`;
  ##               useful to down sample the input data
  ##   periodic -- output the last received metric every `period`;
  ##               useful for filling gaps in input data
```

is just wrong. You won't be able to downsample using `timeout`.

2024-04-16 14:08 UTC, powersj commented
> You won't be able to downsample using timeout.

Your definition above, is that downsampling is about periodic return of data, but I can also read downsample as taking many measurements and reducing them down to a single one. Reducing the rate at which data is transmited. If you receive 100 values during one period, and final returns only the last one, is that not a downsampling?

2024-04-16 17:05 UTC, srebhan commented
@powersj the [definition of downsampling](https://en.wikipedia.org/wiki/Downsampling_(signal_processing)) references a "rate" so my take is that is equidistant. But no matter if this is true or not, the `timeout` strategy will **only output data on timeout** So if you really get data at a regular interval, the aggregator will **never** output anything! That's not downsampling, is it?

2024-04-16 17:24 UTC, powersj commented
> the [definition of downsampling](https://en.wikipedia.org/wiki/Downsampling_(signal_processing)) references a "rate" so my take is that is equidistant. But no matter if this is true or not,

Unfortunately, I will disagree and state that this absolutely definition does matter.

In terms of telegraf, users are generally not doing signal processing. It is probably better to reference a definition specific to metrics and data, for example from our own [blog post on downsamplling](https://www.influxdata.com/blog/downsampling-influxdb-v2-0/).

2024-04-16 17:32 UTC, powersj commented
I want to specifically call out the following quote:

> Additionally, I’ve seen many users ask: “How can I downsample my data to retrieve the mean value and value count from my data at every aggregation interval?”

Replace "mean" with "final".

Given that question from a user, what would you tell them? Use final with `periodic` or final with `timeout`?

I would argue that you could use either, and the key difference is if you want data to fill in gaps via `periodic` or not.

2024-04-16 18:38 UTC, srebhan commented
@powersj so assume a metric that really is coming at a constant rate of 1 sample per minute and use the `timeout` strategy. How would that ever _downsample_ as the aggregator will **never** output any metric!?!?

2024-04-16 19:08 UTC, DStrand1 approved these changes
LGTM!

2024-04-18 08:51 UTC, srebhan approved these changes
Thanks @powersj!

2024-04-18 08:51 UTC, merged