feat(inputs.execd): Allow to provide logging prefixes on stderr
influxdata/telegraf pull request #15834
Opened 2024-09-03 21:19 UTC by srebhan

## Summary

Enable more differentiated logging in external plugins by allowing to provide logging indicators and reflecting those levels in the actual logging on Telegraf side. The PR is backward compatible if no indicator is provided.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #9487

2024-09-04 08:41 UTC, Hipska requested changes

2024-09-04 08:41 UTC, Hipska commented on plugins/inputs/execd/execd.go
> +			e.Log.Errorf("stderr: %q", scanner.Text())
```suggestion
			e.Log.Errorf("stderr: %q", msg)
```

2024-09-04 08:41 UTC, Hipska commented on plugins/inputs/execd/execd.go
> +			fmt.Println("received trace message:", msg[3:])
Is this expected behaviour?

2024-09-04 10:07 UTC, srebhan commented on plugins/inputs/execd/execd.go
> +			fmt.Println("received trace message:", msg[3:])
Of course... not. ;-) Will remove...

2024-09-04 11:03 UTC, Hipska approved these changes

2024-09-09 15:05 UTC, DStrand1 approved these changes

2024-09-09 16:00 UTC, merged