WIP: feat(plugins.nvidia_smi): Implement `Probe()`
influxdata/telegraf pull request #16305
Opened 2024-12-13 18:11 UTC by LandonTClipp

## Summary

## Checklist

- [ ] No AI generated code was used in this PR

## Related issues

resolves #

2024-12-17 14:02 UTC, srebhan requested changes
Thank you for the PR @LandonTClipp! I do have two comments in the code and want to ask you to split the PR into
1. adding the probing framework
2. adding probing support to NVidia SMI

2024-12-17 14:02 UTC, srebhan commented on agent/agent_test.go
> +
I think you don't need the test here as the testing in `running_input_test.go` already covers the case...

2024-12-19 02:26 UTC, LandonTClipp commented
Will do!

2024-12-19 17:42 UTC, LandonTClipp commented
Converting to draft until https://github.com/influxdata/telegraf/pull/16333 is merged.

2025-01-23 14:33 UTC, srebhan approved these changes
Awesome work @LandonTClipp! Thanks!

2025-01-28 04:47 UTC, DStrand1 approved these changes

2025-01-28 04:47 UTC, merged

2025-01-29 11:13 UTC, Hipska commented
It would have been better that this feature was stated/explained in the README of the plugin. (There used to be a checklist item for that)