feat(input.tail): Add `read_start` config for controlling read behavior
influxdata/telegraf pull request #16342
Opened 2024-12-22 08:03 UTC by wen-templari

## Summary

This PR add a `read_start` config for tail plugin. This option gives user more control over the read behavior.

- It can take following options: 
   - save-offset-or-end -- start reading from the persisted offset of the file or, if no offset persisted, start from the end (default) 
   - save-offset-or-beginning -- start reading from the persisted offset of the file or, if no offset persisted, start from the beginning
   - end  -- start reading from the end of the file ignoring any saved offset
   - beginning -- start reading from the beginning of the file ignoring any saved offset

- Use `save-offset-or-end` as default because it matches the previous default `from_beginning = false` behavior.
- After setting `read_start`, the `from_beginning` config will be ignored.
- Change store offset logic. Now the plugin will always store offset ignoring the `from_beginning` config.

## Checklist

- [x] No AI generated code was used in this PR

## Related issues

resolves #16237

2025-01-17 08:52 UTC, srebhan reviewed
Thanks @wen-templari for your contribution! I do have some comments in the code. Please remember to run `make docs` after changing the `sample.conf` file...

Additionally I want to ask you to deprecate the `from_beginning` option as it is replaced by the new one...

2025-01-17 08:52 UTC, srebhan commented on plugins/inputs/tail/sample.conf
> +
How about
```suggestion
  ## Offset to start reading at
  ## The following methods are available:
  ##   beginning          -- start reading from the beginning of the file ignoring any persisted offset
  ##   end                -- start reading from the end of the file ignoring any persisted offset
  ##   saved-or-beginning --use the persisted offset of the file or, if no offset persisted, start from the beginning  of the file
  ##   saved-or-end       -- use the persisted offset of the file or, if no offset persisted, start from the end of the file
  # initial_read_offset = "saved-or-end"

```

2025-01-17 08:52 UTC, srebhan commented on plugins/inputs/tail/tail.go
> +
Please handle this in `Init()`  and afterwards only rely on `ReadStart`. This eases removing of the deprecated `from_beginning` setting later.

2025-01-17 08:52 UTC, srebhan commented on plugins/inputs/tail/tail.go
> +	return seek, nil
How about
```suggestion
	switch t.ReadStart {
	case "beginning":
		return  = &tail.SeekInfo{Whence: 0, Offset: 0}}
	case "end":
		return  = &tail.SeekInfo{Whence: 2, Offset: 0}}
	case "", "saved-or-end":
		if offset, ok := t.offsets[file]; ok {
			t.Log.Debugf("Using offset %d for %q", offset, file)
			return &tail.SeekInfo{	Whence: 0, Offset: offset}
		}
		return  = &tail.SeekInfo{Whence: 2, Offset: 0}}
	case "saved-or-beginning":
		if offset, ok := t.offsets[file]; ok {
			t.Log.Debugf("Using offset %d for %q", offset, file)
			return &tail.SeekInfo{	Whence: 0, Offset: offset}
		}
		return  = &tail.SeekInfo{Whence: 0, Offset: 0}}
	default:
		return nil, errors.New("invalid 'read_start' setting")
	}

	return seek, nil
```

2025-01-17 08:52 UTC, srebhan commented on plugins/inputs/tail/tail_test.go
> -	"github.com/stretchr/testify/require"
This import should stay here as we group into _builtin_ packages, _3rd party_ and telegraf _internal_ ones.

2025-01-20 08:07 UTC, Hipska requested changes

2025-01-20 08:07 UTC, Hipska commented on plugins/inputs/tail/tail.go
> +	FromBeginning       bool     `toml:"from_beginning" deprecated:"1.33.0;1.40.0;use 'InitialReadOffset' instead"`
```suggestion
	FromBeginning       bool     `toml:"from_beginning" deprecated:"1.33.0;1.40.0;use 'initial_read_offset' with value 'beginning' instead"`
```

2025-01-20 08:07 UTC, Hipska commented on plugins/inputs/tail/tail.go
> +	switch initialReadOffset {
No need to pass the offset config?
```suggestion
func (t *Tail) getSeekInfo(file string) (*tail.SeekInfo, error) {
	switch t.InitialReadOffset {
```

2025-01-20 08:07 UTC, Hipska commented on plugins/inputs/tail/tail.go
> +func (t *Tail) tailNewFiles(initialReadOffset string) error {
```suggestion
func (t *Tail) tailNewFiles() error {
```

2025-01-20 12:09 UTC, wen-templari commented on plugins/inputs/tail/tail.go
> +	switch initialReadOffset {
Currently `tailNewFiles` was called by `Gather` with `fromBeginning` set to `true` and called by `Start` with `t.FromBeginning`.
https://github.com/influxdata/telegraf/blob/4905e9f5b9cb90c71944ad877dda79e8222a854e/plugins/inputs/tail/tail.go#L124-L155
https://github.com/influxdata/telegraf/blob/4905e9f5b9cb90c71944ad877dda79e8222a854e/plugins/inputs/tail/tail.go#L165-L197

I passed this config so that `Gather` can let `tailNewFiles` to read from beginning.

2025-01-20 15:24 UTC, Hipska approved these changes

2025-01-22 17:02 UTC, srebhan approved these changes
Thanks a lot @wen-templari!

2025-01-22 17:04 UTC, srebhan commented
@wen-templari I fixed some small formatting issues. Could you please solve the merge conflict?!?

2025-01-23 12:36 UTC, wen-templari commented
Hi @srebhan , I have resolved the merge conflicts.

2025-01-23 13:42 UTC, Hipska approved these changes

2025-01-23 14:35 UTC, srebhan approved these changes

2025-01-27 04:19 UTC, wen-templari commented
Hi @srebhan, I updated the code to fix initialization on the `InitialReadOffset` field. Could you please review it again?

2025-01-27 09:04 UTC, Hipska approved these changes

2025-01-27 19:46 UTC, DStrand1 approved these changes

2025-01-27 19:46 UTC, merged

2025-03-14 11:58 UTC, fetzerch commented on plugins/inputs/tail/tail.go
> -			if !t.Pipe && !fromBeginning {
Has the test for `t.Pipe` been intentionally removed? After the last update it seems to try seeking from pipes which leads to `illegal seek` errors.

2025-03-14 12:59 UTC, Hipska commented on plugins/inputs/tail/tail.go
> -			if !t.Pipe && !fromBeginning {
It looks like this was not intentionally. Please create bug report and if possible also a PR to fix this.

2025-03-21 10:32 UTC, srebhan commented on plugins/inputs/tail/tail.go
> -			if !t.Pipe && !fromBeginning {
@fetzerch could you please open a new issue so we don't loose track of this!?