implemented kairosdb output plugin based on opentsdb plugin
influxdata/telegraf pull request #5827
Opened 2019-05-10 07:32 UTC by 0x6373

### Required for all PRs:

- [X] Signed [CLA](https://influxdata.com/community/cla/).
- [X] Associated README.md updated.
- [X] Has appropriate unit tests. 

unit tests are the same as for the opentsdb plugins (currently only the telnet protocol)

2019-05-20 07:47 UTC, 0x6373 commented
Anyone interested in trying this PR?
I will start rolling out telegraf with this PR into non-prod (>1000 linux hosts) later this week.

2019-05-27 15:30 UTC, raffraffraff commented
> Anyone interested in trying this PR?
> I will start rolling out telegraf with this PR into non-prod (>1000 linux hosts) later this week.

It's almost identical to my fork, except that yours also supports username/password. I've been running mine since March without any issues. This should be drop-in replacement for me, but I'll deploy yours to confirm.

2019-05-27 16:29 UTC, raffraffraff commented
:+1: this is working for me in non-prod

2019-08-03 09:04 UTC, raffraffraff commented
I'm still running my fork of telegraf in production months on, and I'd really like to return to the official telegraf release. Is there an update on this? KairosDB is a not-very-popular competitor of InfluxDB so I can see why there isn't mad a rush to get this merged, but it should be safe to merge a _new_ plugin.

2020-02-18 14:07 UTC, 0x6373 commented
Is there a realistic chance that this pr gets accepted?

2020-02-18 22:26 UTC, danielnelson commented
Yes, sorry about the long delay but we are still wanting to review/merge.

2020-03-04 11:33 UTC, 0x6373 commented
Thanks, good to know.

I just rebased my fork, telegraf build without issues and is now running on a testsystem (with no apparent problems).

2021-01-26 10:12 UTC, 0x6373 commented
Hello, I just rebased my fork with yesterdays master, builds without problems and is currently running on 7 systems (RHEL 7 & RHEL 8) with no issues.

Any chance for a merge?

2021-02-10 09:41 UTC, srebhan commented
@0x6373 does this PR require #3615  to be merged first?

2021-03-05 10:48 UTC, srebhan commented
@0x6373 can you please tell me if you need #3615 for this plugin to work or if it is standalone. Does it superseed #3615? I can give any of the two a review if you are still interested in getting it merged.

Just let me know if you are still interested in working on this one.

2021-03-05 14:50 UTC, 0x6373 commented
@srebhan this pr is standalone and not related to #3615.
Yes, i'm still interested in this being merged, any feedback what should be changed would be very welcome.

2021-03-09 08:15 UTC, srebhan commented on plugins/outputs/kairosdb/README.md
> +Using the Http API is recommended.
Should we then really support this "telnet" mode?

2021-03-09 08:17 UTC, srebhan commented on plugins/outputs/kairosdb/README.md
> +Support for custom data types is not implemented.
This is a user documentation, while this looks like developer documentation. Please document configuration example of this plugin and describe the meaning of config options instead.

2021-03-09 08:20 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +	defaultSeperator = "_"
Those are constants. Alternatively you should use them directly at the one location where you specify those and get rid of the constant declaration.

2021-03-09 08:24 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +	Port int
Please add toml annotations also for the parameters below:
```suggestion
	Prefix string `toml:"prefix"`

	Host string `toml:"host"`
	Port int `toml:"port"`
```

2021-03-09 08:26 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +	HttpBatchSize int // deprecated httpBatchSize form in 1.8
Is this still needed? Or can we use a sensible constant that works for everyone?

2021-03-09 08:26 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +	HttpPath      string
Simply `path` or `endpoint`?

2021-03-09 08:27 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +  prefix = "my.specific.prefix."
Can we have a sensible default (e.g. empty) here and comment the option?

2021-03-09 08:27 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +  port = 4242
If this is the default port, please comment the option.

2021-03-09 08:27 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +  password = ""
Please comment those options.

2021-03-09 08:28 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +  http_path = "/api/v1/datapoints"
Please comment the default settings.

2021-03-09 08:29 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +  debug = false
Please don't add this! This is not useful for the average user and might confuse ppl wrt the telegraf command-line option.

2021-03-09 08:31 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +  host = "http://kairosdb.example.com"
You maybe should also support TLS!? Look at the `TLSConfig` procedure in the `http` input plugin (it's identical for outputs).

2021-03-09 08:33 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +  separator = "_"
If I get this correctly the `separator` should *not* be in the list of characters replaced by `hypenChars` right? Can you please add this limitation as a comment here!?

2021-03-09 08:39 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +	sort.Strings(tagsArray)
If using the `TagList()` function for retrieving the tags you get a `[]*telegraf.Tag` saving some copy operation and simplifies this to:
```suggestion
	for index, tag := range tags {
		tagsArray[index] = tag.Key + "=" + tag.Value
	}
	sort.Strings(tagsArray)
```
Btw: I think the tags are sorted already by `Key` when using `TagList()` but I don't know if you want to rely on this...

2021-03-09 08:40 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +	if !strings.HasPrefix(o.Host, "http") && !strings.HasPrefix(o.Host, "tcp") {
```suggestion
	if !strings.HasPrefix(o.Host, "http://") && !strings.HasPrefix(o.Host, "tcp://") {
```

2021-03-09 08:42 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +	u, err := url.Parse(o.Host)
Maybe you should check if `o.Host` is empty first (e.g. the user commented the option accidentally).

2021-03-09 08:43 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +	defer connection.Close()
Wouldn't it make sense to use the golang `http` client in case you want to connect via HTTP?

2021-03-09 08:47 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +	}
Can you please decide which function to use in an `Init()` function and store a "function-pointer" in the `KairoDB` struct!?

2021-03-09 08:48 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +func (o *KairosDB) WriteHttp(metrics []telegraf.Metric, u *url.URL) error {
This should be a private function.

2021-03-09 08:50 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +				log.Printf("D! KairosDB does not support metric value: [%s] of type [%T].\n", value, value)
Please use the `telegraf.Logger` factility for logging! See e.g. the `file` output plugin for an example.

2021-03-09 08:52 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +	}
Can you please reuse this after setting it up in `Init()` or `Connect()`.

2021-03-09 08:52 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +func (o *KairosDB) WriteTelnet(metrics []telegraf.Metric, u *url.URL) error {
Should be a private function.

2021-03-09 08:53 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +	defer connection.Close()
Is it really necessary to close the TCP connection after every write or can you keep it open?

2021-03-09 08:54 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +				return fmt.Errorf("KairosDB: Telnet writing error %s", err.Error())
Error messages should not start with capital letter. How about 
```suggestion
				return fmt.Errorf("writing to KairosDB using telnet failed: %v", err)
```

2021-03-09 08:55 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +}
Can you please use the `strconv` functions directly!

2021-03-09 08:57 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +		}
As `sanitize()` doesn't do any trimming you might want to do
```suggestion
		if val == "" {
			continue
		}
		tagSet[sanitize(k)] = sanitize(v)
```

2021-03-09 08:59 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +}
Can you please move this function above `SampleConfig()` to have the plugin specific ones grouped.

2021-03-09 09:01 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb.go
> +		"$", "-")
Why don't you do this in one step? You first replace `@*%#$` with `-` only to then use `allowedChars` to replace `-` (and more) with `_`... If you completely leave out the `hyphenChars` step you will end up with the same result, won't you?

2021-03-09 09:06 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb_http.go
> +package kairosdb
This seems a lot of code for sending some message over HTTP. Please check the `loki` output plugin for a good example of sending metrics over HTTP. If you need more, please let me know why as at a first glance KairoDB HTTP API is pretty straight-forward.

2021-03-09 09:07 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb_test.go
> +
Please add a test against a http-test server and check if the received metric adhere's to what you expect!

2021-03-09 09:08 UTC, srebhan commented on plugins/outputs/kairosdb/kairosdb_test.go
> +// }
This test is value-able, so why is it commented?

2021-03-09 09:12 UTC, srebhan requested changes
First of all, thanks @0x6373 for caring!
There are some comments in the code. The big question is, should you really support "telnet" mode? The plugin simplicity would benefit from HTTP-only but I don't know how common the "telnet" interface is!? Is there any reason _not_ to use the HTTP-API?
Please take a look at the `loki` plugin to get a good example for HTTP transport. To me it seems too much code in your implementation...
Regarding the test, I expect a test against a `httptest` server. Again `loki` might serve as an example.

2021-06-01 10:41 UTC, srebhan commented
@0x6373 any update on this PR?

2021-10-15 12:15 UTC, srebhan commented
Anyone willing to work on this PR?

2021-12-20 22:31 UTC, sjwang90 commented
Closing this PR due to inactivity. If someone is interested on taking this work back up, please feel free to re-open the PR and take over the code.

If you would still like this plugin, please submit it as an [external plugin](https://github.com/influxdata/telegraf/blob/master/docs/EXTERNAL_PLUGINS.md) that can be used with `execd` to run seamlessly with Telegraf.

2021-12-20 22:31 UTC, closed without merging