New Solr plugin to collect stats via metrics API #5907
influxdata/telegraf pull request #5908
Opened 2019-05-24 15:29 UTC by frizner

### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2020-02-12 23:20 UTC, The-Little-Rock commented
Hi! Not sure if this PR was forgotten about, but it would be really useful to have. This plugin would work well with the newer versions of Solr, 7.x and beyond. Is there any update on why its not being merged?

2020-02-14 23:46 UTC, danielnelson commented
We are interested in merging, but struggling to find the time to review all the new plugins and handle bugs.  Thanks for being patient, but it may be some time yet.

2020-08-25 07:06 UTC, maxiko commented
It would be nice tio add QUERY and UPDATE

2020-09-02 20:32 UTC, sjmaret commented
Can anyone comment on when this new plugin will be available?

2021-03-02 12:26 UTC, srebhan commented
@frizner are you still interested in getting this merged?

2021-03-02 12:53 UTC, frizner commented
@srebhan , I don't work with Solr anymore but as far as I see the plugin is need by a community. I think it would be great to add the plugin.

2021-03-03 10:18 UTC, srebhan commented
Ok so can anyone else please step up to work with me in getting this merged? @sjmaret, @maxiko, @dustinlebsock anyone?

2021-03-03 14:47 UTC, dustinlebsock commented
Unfortunately, I have also moved on from solr. Though I agree with @frizner, this plugin saves the hassle of finding a work around.

2021-03-03 14:54 UTC, frizner commented
@srebhan , I'm ready to help. What can I do to speed up the process?

2021-03-03 19:42 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	sampleConfig = `
Please define this in a separate `const` and use a two-space indention!

2021-03-03 19:42 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +		# httptimeout = 5
Please name it `timeout` and specify with unit e.g. `timeout = "5s"`.

2021-03-03 19:43 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +		#
Just newline please without the hash.

2021-03-03 19:43 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +		#
Same here, just newline without hash.

2021-03-03 19:44 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	Local       bool
I think this variable is not used...

2021-03-03 19:45 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	Password    string
Please add toml annotations
```suggestion
	Servers     []string `toml:"servers"`
	Username    string `toml:"username"`
	Password    string `toml:"password"`
```
same for the other variables.

2021-03-03 19:46 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	Httptimeout time.Duration
Make it a `config.Duration` so we can use the telegraf infastructure to parse times with suffix e.g. "5s" or "1m".

2021-03-03 19:47 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	Cores       []string
This seems to be no _config_ option, so please make it a private variable.

2021-03-03 19:47 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	client      *http.Client
Do you support TLS? If so please also add `TLSConfig`. Take a look at the `http` input plugin to get an idea.

2021-03-03 19:49 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +type Fields map[string]interface{}
Please just use the maps in the code. Defining types with this names and export them asks for trouble. :-)

2021-03-03 19:51 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	f := make(Metrics)
```suggestion
	f := make(map[string]interface{})
```

2021-03-03 19:52 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +			f[k] = t.Bool()
You don't need those. Telegraf will convert them anyway internally and after you passed them to the map the type is gone anyway.

2021-03-04 08:18 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +		}
So how about
```suggestion
		t := reflect.ValueOf(v)
		switch t.Kind() {
		case reflect.Int, reflect.Float32, reflect.Float64, reflect.String, reflect.Bool:
			f[k] = t
		case reflect.Map:
			subMetsMap, ok := v.(map[string]interface{})
			if !ok {
				acc.AddError(fmt.Errorf("error of converting map"))
				continue
			}
			subMets := parseMetrics(subMetsMap, acc)
			for km, vm := range subMets {
				key := k + delimeter + km
				f[key] = vm
			}
		default:
			acc.AddError(fmt.Errorf("error of parsing, unknow type. %s=%s", k, v))
			continue
		}
```

2021-03-04 08:19 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +}
Please move the code to the single location where it is used to avoid double-checking the length...

2021-03-04 08:22 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +		copyStrMaps(addTags, series[group].tags)
`series[group].tags` should be empty shouldn't it? What is the point in this function call?

2021-03-04 08:24 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	// Parce metrics by a group
```suggestion
	// Parse metrics by a group
```

2021-03-04 08:24 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +func metricsToSeries(metrics Metrics, addTags Tags, acc telegraf.Accumulator) (res []Serie) {
Please make the `acc` always the first argument, except if you have a context.

2021-03-04 08:26 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +		if strings.Contains(k, "solr.core") {
Please invert this
```golang
		if ! strings.Contains(k, "solr.core") {
			continue
		}
		...
```
to save an indention level.

2021-03-04 08:28 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +}
This struct clones `telegraf.Metric`, so why not use it directly?

2021-03-04 08:29 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	}
You could add to the `acc` directly or do it in the parent function instead of copying the series _again_.

2021-03-04 08:30 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +}
I think you should not add a function for this. Instantiate the struct directly.

2021-03-04 08:32 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +		strURL := fmt.Sprintf("%s/solr%s", server, metricPath)
```suggestion
		strURL := server + "/solr" + metricPath
```

2021-03-04 08:33 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +			continue
Please simply return the error and stop the initialization altogether. Make sure to fail early and loudly!

2021-03-04 08:34 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +func (s *Solr) CreateReqs(acc telegraf.Accumulator) ([]*http.Request, error) {
This should be a private function.

2021-03-04 08:37 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	var reqs []*http.Request
Can we please store this in the structure!? AFAICS the requests are not depending on data in `Gather()` and AFAIK `http.Request`s can be reused.

2021-03-04 08:38 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +		return fmt.Errorf("no Solr metrics handled")
Is this really an error or can this happen during normal operation?

2021-03-04 08:39 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	}
Please do this in an `Init()` function that is only executed once.

2021-03-04 08:39 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	wg.Add(len(s.reqs))
Please move this into the for loop adding `1` during each execution of the loop.

2021-03-04 08:40 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics.go
> +	return err
This should be `nil` shouldn't it?

2021-03-04 08:42 UTC, srebhan commented on plugins/inputs/solrmetrics/solrmetrics_test.go
> +)
```suggestion
const path = "/solr/admin/metrics"
```

2021-03-04 08:50 UTC, srebhan requested changes
@frizner thanks for helping. Please find comments of my first review round in the comments. Having not yet compared the code I wonder if this can be integrated into the existing `solr` input plugin? Have you looked into this?

2021-04-28 13:02 UTC, srebhan commented
@frizner any news on this one?

2021-04-28 13:27 UTC, frizner commented
@srebhan, sorry, was a very busy.

2021-04-28 13:32 UTC, srebhan commented
@frizner no worries, I just want to make sure that the PR is not rotting. ;-)

2021-05-11 06:40 UTC, srebhan commented
@frizner same here. Please drop me a note whenever you are good for another review round!

2021-12-20 22:39 UTC, sjwang90 commented
Closing this PR due to inactivity. If someone is interested on taking this work back up, please feel free to re-open the PR and take over the code.

2021-12-20 22:39 UTC, closed without merging