feat: add flattenjson plugin serializers
influxdata/telegraf pull request #6134
Opened 2019-07-17 13:56 UTC by FortunatCE

### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2019-07-17 20:48 UTC, danielnelson commented
There are so many potential formats for outputting JSON, I wonder if we could have a JMESPath expression that could transform the output JSON from a known base layout into a custom layout.  Would it be possible for you to check if JMESPath could do this transformation from the normal JSON serializer output?

2019-07-19 13:10 UTC, FortunatCE commented
> There are so many potential formats for outputting JSON, I wonder if we could have a JMESPath expression that could transform the output JSON from a known base layout into a custom layout. Would it be possible for you to check if JMESPath could do this transformation from the normal JSON serializer output?

Thanks for your quick response.
I think it will be more appropriate to use Jolt expression in order to transform the default json format into a custom one.
The main idea behind this PR is to have a unitary metric record, in which you will have a metric name and its value.
Since JMESPath provides only querying expressions on json documents, I'm not sure that we could use it to generate unitary metric records.

2019-07-19 17:45 UTC, danielnelson commented
Makes sense, appreciate the advice.  Jolt might be hard to integrate, since it is written in Java, but I did find the [qntfy/kazaam](https://github.com/qntfy/kazaam) project that could be an option.

2019-07-24 16:09 UTC, FortunatCE commented
> Makes sense, appreciate the advice. Jolt might be hard to integrate, since it is written in Java, but I did find the [qntfy/kazaam](https://github.com/qntfy/kazaam) project that could be an option.

Thanks for your proposition.
We tried JMESPath and qntfy/kazaam, but we couldn't managed to achieve the json transformation we need. After several tests, it seems that both libraries are limited and not suited for this tranformation use case.

What we wanted to achieve with this PR is to transform this document:
{
  "fields": {
    "reads": 973,
    "write_bytes": 2097152,
	"foobar": 555
  },
  "name": "diskio",
  "tags": {
    "host": "myhost",
    "name": "vda1"
  },
  "timestamp": 1556936700000
}

into the following expected output:
{"metric_family": "diskio", "timestamp": 1556936700000, "tags_host": "myhost", "tags_name": "vda1", "metric_name": "diskio_reads", "metric_value": 973}
{"metric_family": "diskio", "timestamp": 1556936700000, "tags_host": "myhost", "tags_name": "vda1", "metric_name": "diskio_write_bytes", "metric_value": 2097152}
{"metric_family": "diskio", "timestamp": 1556936700000, "tags_host": "myhost", "tags_name": "vda1", "metric_name": "diskio_foobar", "metric_value": 2097152}

The idea is to have basic flattened unitary json metrics data points, so it can be pushed to multiple datastores (like Druid, Elasticsearch, OpenTSDB, ... etc). We can then imagine another output that takes in a kasaam or JMESPath expression and transform this unitary metric data point to another format.

Do you think that if we change the name of the output format from flattenjson to jsonunitarymetric, it would be more appropriate ?

2019-07-24 20:48 UTC, danielnelson commented
> We tried JMESPath and qntfy/kazaam, but we couldn't managed to achieve the json transformation we need.

Too bad.  I think we need to keep looking for a good generic solution for building out JSON from Telegraf metrics.  However, I don't think we would accept another json serializer that doesn't allow for user control in some way, any format we pick would just be too specific to a single users need.

2019-07-30 15:43 UTC, FortunatCE commented
Based on your response, we have implemented a new serializer that allow user to customize the output format with JMESPath grammar expression based on default unitary metric output.
Commons parameters can be customized with JMESPath grammar by specifying "jmespath_expression" parameter in the Telegraf configuration file and tags parameter can be prefixed by specifying "tags_prefix" parameter in the Telegraf configuration file.
There are some event example on the README.md file that explain how the serializer works.

Do you have any recommendation about this new update please ?
Thanks

2019-08-05 23:58 UTC, danielnelson commented
I think this shows our prior concerns were founded, that JMESPath isn't really be suitable for your use case.  The evidence being that you needed to include options specifically for prefixing the tags with a string since this doesn't seem possible.

2021-04-08 09:25 UTC, srebhan commented
@FortunatCE are you still interested in getting this merged?

2021-04-08 16:39 UTC, FortunatCE commented
> @FortunatCE are you still interested in getting this merged?

Hello @srebhan, 
Yes I am still interested in getting this pull request merged
Regards,

2021-04-14 11:49 UTC, srebhan commented on internal/config/config.go
> +	}
How about adding a fields-prefix the same way? Or alternatively define this as a "prefix for elements not handled otherwise"... Does that make sense?

2021-04-14 11:50 UTC, srebhan commented on plugins/serializers/customjson/customjson.go
> +
Please remove this newline and all others not helping to structure the code.

2021-04-14 11:51 UTC, srebhan commented on plugins/serializers/customjson/customjson.go
> +		return nil, fmt.Errorf("D! [serializer.customjson] Dropping invalid metric: %s", metric.Name())
Please use only the error message for errors e.g.
```suggestion
		return nil, fmt.Errorf("dropping invalid metric: %s", metric.Name())
```

2021-04-14 11:53 UTC, srebhan commented on plugins/serializers/customjson/customjson.go
> +			return nil, fmt.Errorf("D! [serializer.customjson] Dropping invalid metric: %s", metric.Name())
Same as above. Please rethink if you want to stop serialization if one metric is invalid or not. Both is fine for me...

2021-04-14 11:54 UTC, srebhan commented on plugins/serializers/customjson/customjson.go
> +
Remove newline as it does not help structuring the code but rather clutters it.

2021-04-14 11:54 UTC, srebhan commented on plugins/serializers/customjson/customjson.go
> +		dataGroup["timestamp"] = float64(metric.Time().UnixNano()) / float64(1000000)
Why do you convert the time here?

2021-04-14 11:55 UTC, srebhan commented on plugins/serializers/customjson/customjson.go
> +		dataGroup["metric_value"] = fieldValue
Why do you enforce "one-field per output"?

2021-04-14 11:56 UTC, srebhan commented on plugins/serializers/customjson/customjson.go
> +		}
You might want to do this decision in an `Init()` function and store the function pointer in the serializer struct...

2021-04-14 11:57 UTC, srebhan commented on plugins/serializers/customjson/customjson.go
> +		metricJson = append(metricJson, '\n')
Is this really necessary?

2021-04-14 12:00 UTC, srebhan commented on plugins/serializers/customjson/customjson.go
> +		}
Which error are you checking here?

2021-04-14 12:02 UTC, srebhan commented on plugins/serializers/customjson/customjson.go
> +}
Why is a string value invalid? Why do you convert boolean values to numbers? I don't get the idea behind this function... Both string and boolean values are fine for encoding in json as value...

2021-04-14 12:02 UTC, srebhan commented on plugins/serializers/registry.go
> +	case "customjson":
Should we maybe use "jmetransformer" or similar?

2021-04-14 12:04 UTC, srebhan requested changes
I left some comments in the code, nothing too big. Please rebase your code on the latest master and convert to go-modules for handling the dependencies.

2021-04-15 15:28 UTC, FortunatCE commented
> I left some comments in the code, nothing too big. Please rebase your code on the latest master and convert to go-modules for handling the dependencies.



> I left some comments in the code, nothing too big. Please rebase your code on the latest master and convert to go-modules for handling the dependencies.

Thanks for your review !
I will work on it based on your recommendations. 
Regards,

2021-04-15 15:30 UTC, FortunatCE commented
> I left some comments in the code, nothing too big. Please rebase your code on the latest master and convert to go-modules for handling the dependencies.

Thanks for your review @srebhan !
I will work on it based on your recommendations.
Regards,

2021-06-01 10:30 UTC, srebhan commented
@FortunatCE any update on this?

2021-10-15 12:15 UTC, srebhan commented
@FortunatCE do you think you can work on this PR?

2021-11-30 15:07 UTC, srebhan commented
Any volunteer for taking over this PR?

2022-01-24 20:42 UTC, powersj commented
Hi,

This PR has not been touched in a while and as a result I am going to close it. We are happy to review again once someone picks this back up with the suggested changes and rebased on master.

Thanks!

2022-01-24 20:42 UTC, closed without merging