Regex measurement
influxdata/telegraf pull request #6831
Opened 2019-12-27 20:55 UTC by bjeram

### Required for all PRs:

- [x ] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [?] Has appropriate unit tests.

Address Issue #6145 InfluxDB Database/Measurement Settings Based on MQTT Topic
using a modified regex processor that can change the measurement name ( if result_key = "measurement" ). At the moment it woeks just for tags, but can be extended to fileds as well.

2020-03-09 10:47 UTC, merouaneagar commented
Hello,
We need this functionality

```
  [[processors.regex.tags]]
    ## tag that we use to 'calculate' the name of the measurment
    key = "topic"
    pattern = 'sensors/(\w+)/(\w+)/(\w+)'
    replacement = "${2}"
    result_key = "measurement"
```

Regards

2020-10-26 02:41 UTC, sjwang90 commented
Looks like this PR is a duplicate fo #6830. Feel free to open PR back up if I'm incorrect.

2020-10-26 07:25 UTC, bjeram commented
It is duplicate of #6830, but #6830 was closed (as it was created by mistake).
So I suggest to reopen this PR, and if possible merge it

2021-01-22 05:10 UTC, sjwang90 requested changes

2021-01-22 05:10 UTC, sjwang90 commented on plugins/processors/regex/README.md
> +  ## if measurement is given to reult_key then it is changed the name os the measurement (not a tag!!)
please fix the typos in the comments

2021-12-07 20:45 UTC, srebhan commented
@bjeram I think this can be closed as #9561 covers your functionality. Furthermore, #9995 provides an elegant way to extract information from MQTT topics. Please reopen if you disagree!

2021-12-07 20:45 UTC, closed without merging