improve mntr regex to match user specific keys.
influxdata/telegraf pull request #7533
Opened 2020-05-18 06:31 UTC by powerLambda

### Required for all PRs:

Found zookeeper input plugin error as below:
[inputs.zookeeper] Error in plugin: unexpected line in mntr response: "zk_avg_pull-daily-attendence-data-testByQA_read_per_namespace\t137.1803"

This PR is to improve mntr regex to match user specific keys.

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2020-05-20 06:48 UTC, powerLambda commented
Bug link #7550

2020-11-14 16:00 UTC, srebhan requested changes

2020-11-14 16:00 UTC, srebhan commented on plugins/inputs/zookeeper/zookeeper.go
> +var zookeeperFormatRE = regexp.MustCompile(`^zk_([\w\.\-]+)\s+([\w\.\-]+)`)
I think this is not correct as you now also accept items with "." or "-" only. I guess the correct regex should be
```suggestion
var zookeeperFormatRE = regexp.MustCompile(`^zk_(\w[\w\.\-]*)\s+([\w\.\-]+)`)
```

2020-11-26 19:08 UTC, srebhan commented
@powerLambda can you please check the comment so we can go forward with this PR!?

2020-12-11 12:40 UTC, srebhan commented
@powerLambda ping!

2021-01-20 04:31 UTC, sjwang90 commented
@powerLambda - can you please let us know if you can make the changes to @srebhan's comment. Otherwise we can look for someone on the influx side to finish it up.

2021-01-21 17:04 UTC, powerLambda commented
@sjwang90 sorry for the late reply, crazy busy for a while.

2021-01-22 09:27 UTC, srebhan approved these changes
Looks good to me.

2021-01-27 20:39 UTC, ssoroka approved these changes

2021-01-27 20:39 UTC, merged