Apache Avro parser plugin
influxdata/telegraf pull request #7732
Opened 2020-06-24 18:14 UTC by emanuele-falzone

Hi 😃

This PR adds the ability to parse Apache Avro encoded messages.
This plugin is inspired from the use of Apache Avro with Kafka and [Confluent Schema Registry](https://docs.confluent.io/current/schema-registry/index.html).
Issue [#1630](https://github.com/influxdata/telegraf/issues/1630) discusses the need of such parser.

This PR has
- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

2020-07-31 00:03 UTC, rodrigobrochado commented
Also, does a parser PR need to update the [DATA_FORMATS_INPUT](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md) file?

2020-08-25 17:24 UTC, emanuele-falzone commented on plugins/parsers/avro/parser.go
> +		m, err := metric.New(p.Measurement, tags, fields, metricTime)
I think it is a good idea, I will update the code as suggested.

2020-08-25 17:24 UTC, emanuele-falzone commented on plugins/parsers/avro/parser.go
> +	schema, err := schemaRegistry.getSchema(schemaID)
Can you explain your use case a little more? Are you reading messages from a Kafka topic? If so, how are these messages serialized?

2021-01-22 04:19 UTC, sjwang90 commented
@rodrigobrochado Yes, a parser would need to be added to the DATA_FORMATS_INPUT readme.

2021-03-18 21:58 UTC, sjwang90 commented
@emanuele-falzone @rodrigobrochado Do either of you have any other changes to this PR you'd like to make? We'll look to get someone on the influx side to do a review if this PR is ready for review.

2021-03-18 22:10 UTC, rodrigobrochado commented
@sjwang90 I was not able to answer some of @emanuele-falzone points yet. I think it still needs some adjustments.   

I'm sorry for the delay, I was put in another sector of our company but I'm coming back soon. When back, the matter on this PR will certainly be our priority.

2021-03-19 18:06 UTC, ssoroka requested changes
great start, needs some updates.

2021-03-19 18:06 UTC, ssoroka commented on plugins/parsers/avro/schema_registry.go
> +		return "", fmt.Errorf("malformed respose from schema registry")
include actual type. return or log.

2021-05-26 16:47 UTC, sjwang90 commented
@emanuele-falzone Can you please address the comments above? Let us know if you are no longer interested in working on this.

2021-12-20 23:07 UTC, sjwang90 commented
Closing this PR due to inactivity. If someone is interested on taking this work back up, please feel free to re-open the PR and take over the code.

2021-12-20 23:07 UTC, closed without merging

2022-09-13 19:21 UTC, athornton commented
I'm starting to look at this, address the review commentary, and get it rebased on current telegraf: https://github.com/lsst-sqre/telegraf/tree/features/avro

I will issue a new PR if and when I have it working.

2022-09-15 17:25 UTC, athornton commented
New PR is at https://github.com/influxdata/telegraf/pull/11816