Improve procstat
influxdata/telegraf pull request #7890
Opened 2020-07-24 09:12 UTC by DEvil0000

* cgroups now support glob
* systemd_unit in combination with systemd_all will now report for all children and not just the main pid of the service
* in case cgroups or systemd_unit+all will return a group of pids they get tagged with their actual cgroup/service matched (cgroup_full)

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [ ] Has appropriate unit tests.

2021-01-15 14:45 UTC, TelmoM commented
Hi @sjwang90, is this update going to be merged soon?
Thank you

2021-01-15 20:59 UTC, sjwang90 commented
Sorry for the delay - we'll get this reviewed.

2021-07-06 16:25 UTC, sspaink requested changes
Thank you for working on this pull request! It does look it will improve the procstat plugin, I've added some review comments for you to look at.

2021-07-06 16:25 UTC, sspaink commented on plugins/inputs/procstat/procstat.go
> +type PIDS_TAGS_ERR_GROUP struct {
I think that putting PID and tags together in a struct makes sense, but it might be more idiomatic to keep error separate.

2021-07-06 16:25 UTC, sspaink commented on plugins/inputs/procstat/procstat.go
> +func (p *Procstat) SimpleFindPids(f PIDFinder) ([]PID, map[string]string, error) {
Can you explain why the word "simple" is being used to describe this function ? It seems it could return a `PIDS_TAGS_ERR_GROUP` struct as well.

2021-07-06 16:51 UTC, DEvil0000 commented
@sspaink thanks for the review!
However go is not one of the programming languages I use (at all) so I tried to do it in a kind of clean way and sticking close to the original code. About 1y after creating the PR I don't feel like I want to mess with those details (at least currently I don't have time to do so - sorry). Please fix or change what you feel meets the projects coding style or standards best e.g. in a additional commit.
I would absolutely appreciate having this features in the master so I may be able to go back to the official version instead of maintaining my own one.

2021-07-06 20:45 UTC, sspaink commented
@DEvil0000 thank you for letting us know, sorry for taking so long with the review. I'll look into taking over the pull request and work with the team to get it merged. I will be sure mention your contribution and let you know once it is in master/released.

2021-07-06 22:05 UTC, DEvil0000 commented
Thank you! Thank you for taking care!

2021-07-10 00:38 UTC, sspaink commented on plugins/inputs/procstat/procstat.go
> +type PIDS_TAGS_ERR_GROUP struct {
Looking more into this, I see why it is structured this way.

2021-07-10 00:39 UTC, sspaink commented on plugins/inputs/procstat/procstat.go
> +func (p *Procstat) SimpleFindPids(f PIDFinder) ([]PID, map[string]string, error) {
Looking more into this, I see why it is structured this way.

2021-07-10 00:58 UTC, sspaink commented
#9488 will continue this pull request.

2021-07-10 00:58 UTC, closed without merging