Fix Sumo Logic output plugin not splitting requests properly (#25)
influxdata/telegraf pull request #8115
Opened 2020-09-11 14:08 UTC by pmalek-sumo

This should fix 2 problems:

* sending the last request with empty body (the condition when calculating boundary was incorrect)
* sending requests bigger than `MaxRequstBodySize` (now it will only happen when it's configured so small so that it's not able to accomodate even one metric - a warning will be printed out in such case but the request will go through).

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [x] Has appropriate unit tests.

2020-09-14 16:00 UTC, ssoroka requested changes
Once the requests are chunked, if any one succeeds, you need to **log** the error (not return it) and continue to attempt to deliver all the rest of the chunks. This means dropping the ones that don't deliver correctly, as there's no way to partially deliver a batch.

A better approach might be to ensure your batch size is small enough that you don't ever need to chunk, as once you start chunking your only options when a chunk fails to deliver is to: 1. Drop chunks that don't make it and accept the batch as delivered (returning no error), or 2. accept delivering duplicates and return an error, retrying the entire batch.

2020-09-14 16:54 UTC, pmalek-sumo commented
> A better approach might be to ensure your batch size is small enough that you don't ever need to chunk

Can you explain a bit more how should that work?

> 1. Drop chunks that don't make it and accept the batch as delivered (returning no error), or 2. accept delivering duplicates and return an error, retrying the entire batch.

I'd rather just do 1.

2020-09-15 14:22 UTC, pmalek-sumo commented
I've changed the logic to just log the error when a chunk fails to get sent.

On top of that: I have a patch that checks each request's body additionally to checking the request count, I can add it here or push a separate PR if that would be better.

2020-09-24 17:02 UTC, ssoroka requested changes
Nearly there. two small change requests.

2020-09-24 17:02 UTC, ssoroka commented on plugins/outputs/sumologic/sumologic_test.go
> +				requestCount++
might need `atomic.AddInt32` / `atomic.LoadInt32` for these counters. It's a different goroutine, and isn't race safe.

2020-09-24 20:10 UTC, ssoroka approved these changes

2020-09-24 20:13 UTC, merged