Fix suricata crash on startup when unix socket missing
influxdata/telegraf pull request #8273
Opened 2020-10-15 14:08 UTC by odedlaz

Suricata plugin tries to dial into the configured stats socket
if one is missing, the plugin doesn't start up instead of
accumulating the error.

### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2020-11-14 15:36 UTC, srebhan commented
Hey @odedlaz!

The build failed with errors and I think your change is not quite right. With your change, a new "connection" is made everytime `Gather()` is called without closing this connection. I'd rather split the functions into a `connect()/disconnect()` and "get and parse metric" part.
Then you try to connect in init. If this does not work, you silently ignore the error and set a flag `connected` to false (or true if connection was successful). Then in `Gather()` you should check if connected is true and otherwise try to connect (maybe also incrementing the error count). If reading the socket fails, set connected to false again and either retry connection or drop out of `Gather()`...

Do you think you can rework the PR?

2020-11-14 16:01 UTC, srebhan requested changes
Hey @odedlaz!

The build failed with errors and I think your change is not quite right. With your change, a new "connection" is made everytime Gather() is called without closing this connection. I'd rather split the functions into a connect()/disconnect() and "get and parse metric" part.
Then you try to connect in init. If this does not work, you silently ignore the error and set a flag connected to false (or true if connection was successful). Then in Gather() you should check if connected is true and otherwise try to connect (maybe also incrementing the error count). If reading the socket fails, set connected to false again and either retry connection or drop out of Gather()...

Do you think you can rework the PR?

2020-11-17 08:09 UTC, odedlaz commented
@srebhan, thank you so much for answering! after further debugging I came to the conclusion that this PR is redundant since the problem was on my end. I'm closing the PR.

2020-11-17 08:09 UTC, closed without merging

2020-11-17 09:06 UTC, srebhan commented
@odedlaz can you elaborate on what the problem was? I mean telegraf should _never_ crash I think, so maybe we can catch the "problem on your side" and at least avoid crashing...