Systemd
influxdata/telegraf pull request #8381
Opened 2020-11-10 09:00 UTC by Mic92

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2020-11-10 09:06 UTC, Mic92 commented
It fixes this error:

```
Nov 10 10:05:40 rock telegraf[20327]: 2020-11-10T09:05:40Z E! [inputs.systemd_units] Error in plugin: Error parsing field 'load', value not in map: iscsi.service
Nov 10 10:05:40 rock telegraf[20327]: 2020-11-10T09:05:40Z E! [inputs.systemd_units] Error in plugin: Error parsing field 'load', value not in map: modprobe@drm.service
Nov 10 10:05:40 rock telegraf[20327]: 2020-11-10T09:05:40Z E! [inputs.systemd_units] Error in plugin: Error parsing field 'load', value not in map: nfs-server.service
Nov 10 10:05:40 rock telegraf[20327]: 2020-11-10T09:05:40Z E! [inputs.systemd_units] Error in plugin: Error parsing field 'load', value not in map: plymouth-quit-wait.service
Nov 10 10:05:40 rock telegraf[20327]: 2020-11-10T09:05:40Z E! [inputs.systemd_units] Error in plugin: Error parsing field 'load', value not in map: plymouth-quit.service
Nov 10 10:05:40 rock telegraf[20327]: 2020-11-10T09:05:40Z E! [inputs.systemd_units] Error in plugin: Error parsing field 'load', value not in map: plymouth-start.service
Nov 10 10:05:40 rock telegraf[20327]: 2020-11-10T09:05:40Z E! [inputs.systemd_units] Error in plugin: Error parsing field 'load', value not in map: rbdmap.service
Nov 10 10:05:40 rock telegraf[20327]: 2020-11-10T09:05:40Z E! [inputs.systemd_units] Error in plugin: Error parsing field 'load', value not in map: syslog.service
Nov 10 10:05:40 rock telegraf[20327]: 2020-11-10T09:05:40Z E! [inputs.systemd_units] Error in plugin: Error parsing field 'load', value not in map: systemd-hwdb-update.service
Nov 10 10:05:40 rock telegraf[20327]: 2020-11-10T09:05:40Z E! [inputs.systemd_units] Error in plugin: Error parsing field 'load', value not in map: systemd-sysusers.service
```

2020-11-12 17:56 UTC, srebhan requested changes

2020-11-12 17:56 UTC, srebhan commented on plugins/inputs/systemd_units/systemd_units_linux.go
> +		}
The problem is that we remove things _after_ the length check. There might be cases where you get four fields, but an asterix in the beginning and then end up with only three fields left in _data_.

How about adding
```suggestion
if strings.HasPrefix(line, "*") {
     line = strings.replace(line, "*", "", 1)
}
```
above, directly after the assignment to line (line 148 I think) and **before** creating _data_?

2020-11-12 19:46 UTC, srebhan commented
Does this also relate to issue #7990?

2020-11-12 20:43 UTC, ssoroka approved these changes

2020-11-12 20:45 UTC, srebhan approved these changes

2020-11-12 20:52 UTC, ssoroka commented
this might be resolved now as of #7991

2020-11-13 07:24 UTC, Mic92 commented
Yes.

2020-11-13 07:24 UTC, closed without merging