Allow timestamping gnmi notifications locally
influxdata/telegraf pull request #8420
Opened 2020-11-17 00:16 UTC by rski

Sometimes it can be useful to use a local, on receive timestamp for
gnmi notifications. This is the case for sample subscriptions. The
gnmi spec requires that the update timestamps are the time when the
value from the underlying data source (e.g. counter hardware) changed.
This value might not change for a long time, resulting in a timestamp
way back in the past. For such situations, it can be useful to use the
current time on the server, turning the semantics of the timestamp
into "This was the value on the device at time T according to the
collector" from "This was when the value last changed on the device."

Fixes #8411

### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2020-11-19 18:20 UTC, srebhan commented
@rski thanks for submitting this PR. Unfortunately it seems you have not yet signed the [CLA](https://influxdata.com/community/cla/) which prevents proper review of your changes. Could you please fill the CLA!

2020-11-20 08:26 UTC, srebhan requested changes
Please also add a description of the newly added option to the `README.md` file and to the `sampleConfig` variable.

2020-11-20 11:43 UTC, rski commented
> @rski thanks for submitting this PR. Unfortunately it seems you have not yet signed the [CLA](https://influxdata.com/community/cla/) which prevents proper review of your changes. Could you please fill the CLA!

I will, I'm in the process of getting the CCLA signed too. I'll update the README as well, I knew I was forgetting something :)

2020-11-21 11:03 UTC, srebhan commented
No worries. Looks quite good already. :-)

2020-11-23 04:23 UTC, rski commented
ok, I updated the docs, I'll let you know when I have an update on the CCLA. That will probably be next week.

2020-11-25 13:49 UTC, srebhan commented
Code looks good. Waiting for the administrative requirements... :-)

2020-12-07 17:01 UTC, rski commented
the CCLA from Arista and my personal CCL are now all submitted, I gave the changes a rebase + conflict resolution just now to the latest telegraph master

2020-12-11 12:46 UTC, srebhan approved these changes
LGTM

2020-12-17 14:50 UTC, rski commented
gentle bump?

2020-12-18 17:07 UTC, ssoroka commented
I'm wondering if this should just be a processor plugin. This comes up many times across a lot of different plugins.

2020-12-18 17:45 UTC, srebhan commented
@rski you've not been forgotten. :-) The guys are about to release 1.17 and PRs merges are held back until the release is done AFAIK.

2021-01-06 20:18 UTC, ksator commented
@srebhan hello, several of us are looking forward for this merge :-) 
Many thanks in advance for your help.

2021-01-11 13:45 UTC, srebhan commented
@ksator well I'm only the poor reviewer and that's where my power ends... ;-)
@ssoroka can we merge this for now until we solve this more generally?

2021-01-13 18:56 UTC, ssoroka commented
I think we're going to go in a different direction with this, but if you want to use this branch until another solution is ready, you can grab the relevant build artifact directly and use it until the other solution is ready.

https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632-0.aarch64.rpm
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632-0.armel.rpm
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632-0.armv6hl.rpm
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632-0.i386.rpm
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632-0.ppc64le.rpm
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632-0.s390x.rpm
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632-0.x86_64.rpm
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_darwin_amd64.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_freebsd_amd64.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_freebsd_i386.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_linux_amd64.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_linux_arm64.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_linux_armel.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_linux_armhf.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_linux_i386.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_linux_mips.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_linux_mipsel.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_linux_ppc64le.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_linux_s390x.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_static_linux_amd64.tar.gz
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_windows_amd64.zip
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf-1.16.3%7E9ed9a632_windows_i386.zip
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.16.3%7E9ed9a632-0_amd64.deb
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.16.3%7E9ed9a632-0_arm64.deb
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.16.3%7E9ed9a632-0_armel.deb
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.16.3%7E9ed9a632-0_armhf.deb
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.16.3%7E9ed9a632-0_i386.deb
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.16.3%7E9ed9a632-0_mips.deb
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.16.3%7E9ed9a632-0_mipsel.deb
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.16.3%7E9ed9a632-0_ppc64el.deb
https://74283-33258973-gh.circle-artifacts.com/0/build/dist/telegraf_1.16.3%7E9ed9a632-0_s390x.deb

2021-01-13 20:08 UTC, sjwang90 commented
@rski Thanks so much for your PR but as the comment above mentioned we thought we should go another route that is outlined in #8689.

I'll leave this PR open until #8689 gets addressed.

2021-02-16 21:36 UTC, sjwang90 commented
If anyone is looking for this feature on gnmi specifically, pleas use the builds from above. I would like to close this for now. 

If anyone would like to work on #8689 for local timestamping to be used across plugins more generally we would gladly welcome a PR.

2021-02-16 21:36 UTC, closed without merging