Added name parameter to NATS output
influxdata/telegraf pull request #8429
Opened 2020-11-18 06:33 UTC by oplehto

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

Added `name` parameter to the NATS output plugin. The connection name simplifies monitoring, debugging and reporting. 

See: https://docs.nats.io/developing-with-nats/connecting/name

2020-11-18 17:08 UTC, srebhan approved these changes

2020-11-19 16:54 UTC, ssoroka requested changes

2020-11-19 16:54 UTC, ssoroka commented on plugins/outputs/nats/nats_test.go
> +		Name:       "telegraf",
this default should be `""` to match the config.

2020-11-19 16:54 UTC, ssoroka commented on plugins/outputs/nats/nats.go
> +
This needs to be added to the readme as well.

2020-11-26 19:03 UTC, srebhan commented
@oplehto could you please add the new option to the `README.md` file as well!?

2020-11-27 08:24 UTC, srebhan approved these changes
Looks good.

2020-11-27 16:24 UTC, ssoroka approved these changes

2020-11-27 16:24 UTC, merged

2020-11-27 16:24 UTC, ssoroka commented
Thank you!