add ability to name the value field
influxdata/telegraf pull request #8469
Opened 2020-11-24 19:04 UTC by jessingrass

### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2020-11-24 19:21 UTC, ssoroka requested changes
looks like I gave you some conflicting naming advice. comments!

2020-11-24 19:21 UTC, ssoroka commented on config/config.go
> +	c.getFieldString(tbl, "value_field", &pc.ValueValueName)
```suggestion
	c.getFieldString(tbl, "value_value_field", &pc.ValueValueField)
```

2020-11-24 19:21 UTC, ssoroka commented on plugins/parsers/registry.go
> +	ValueValueName string `toml:"value_value_name"`
```suggestion
	ValueValueField string `toml:"value_value_field"`
```

2020-11-24 19:21 UTC, ssoroka commented on plugins/parsers/registry.go
> +			config.DataType, config.DefaultTags, config.ValueValueName)
```suggestion
			config.DataType, config.DefaultTags, config.ValueValueField)
```

2020-11-25 21:49 UTC, srebhan commented
What are you trying to achive here??? If you want to override a field-name maybe `fieldname_override` similar to `name_override`?

2020-12-04 18:01 UTC, jessingrass commented
@srebhan issue 7702 (linked above) is the issue I'm working to address

2020-12-09 19:39 UTC, ssoroka approved these changes

2020-12-09 19:40 UTC, ssoroka commented
oh. you'll also need to default the value field name to "value"

2020-12-18 17:17 UTC, srebhan commented on plugins/parsers/registry.go
> +	ValueValueField string `toml:"value_value_field"`
This is a horrible user-facing option name! How about `value_fieldname`?

2020-12-18 17:21 UTC, srebhan commented on plugins/parsers/value/parser.go
> +	fields := map[string]interface{}{v.ValueField: value}
You need to handle the default i.e. the user didn't specify anything...
```suggestion
	fieldname := "value"
	if v.ValueField != "" {
		fieldname = v.ValueField
	}
	fields := map[string]interface{}{fieldname: value}
```

2020-12-18 17:24 UTC, srebhan requested changes
You need to handle the default-case where the user didn't specify anything. Furthermore, you should update the README.md to introduce the new option and give a short explanation of what it does. Last but not least I really think `value_value_field` is a horrible name for an option and suggest changing it to `value_fieldname`.

2021-01-26 09:20 UTC, srebhan commented
@jessingrass any news on this one?

2021-03-03 15:58 UTC, srebhan approved these changes
Looks good to me!

2021-03-03 17:07 UTC, helenosheaa approved these changes
Looks good!

2021-03-04 13:48 UTC, srebhan commented
@jessingrass can you please resolve the merge conflicts!

2021-03-12 14:23 UTC, Jagularr commented
The fix for this has been made in #8979 when we had the related issue assigned for pairing yesterday. I did not realize there was already a PR out for this, my apologies!!!

2021-03-12 14:23 UTC, closed without merging