Add FLOAT64-IEEE support to inputs.modbus (#8361) (by @Nemecsek)
influxdata/telegraf pull request #8474
Opened 2020-11-25 18:33 UTC by soerman

This adds FLOAT64-IEEE support (issue #8361). 
**Please note that @Nemecsek is the original author** &rarr;  See discussion in #8361.

### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2020-11-25 18:52 UTC, garciaolais commented
@soerman please consider adding some test cases for this new type

2020-11-25 21:32 UTC, srebhan commented
We also need the description in the `README.md` file. Futhermore, you need a CLA otherwise we cannot merge this PR...

2020-11-25 22:40 UTC, ssoroka commented on plugins/inputs/modbus/modbus.go
> +	return float64(float64(v) * s)
Everything's a float64 here, so just 
```suggestion
	return v * s
```

2020-11-25 22:40 UTC, ssoroka approved these changes

2020-11-25 22:42 UTC, ssoroka requested changes
Actually, we should have some test cases to avoid any regressions

2020-11-28 21:06 UTC, youcann commented
Seems good now

2020-11-30 11:58 UTC, srebhan approved these changes
LGTM.

2020-11-30 21:22 UTC, ssoroka approved these changes

2020-11-30 21:22 UTC, merged