Add CSGO SRCDS input plugin
influxdata/telegraf pull request #8525
Opened 2020-12-08 07:30 UTC by oofdog

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2020-12-08 11:00 UTC, zak-pawel commented
@oofdog Let me know when plugin is finished (don't forget to add proper `README.md` and some basic unit tests). I'd love to use it with my server :)

2021-02-23 18:42 UTC, oofdog commented
@zak-pawel Ready to go.

2021-02-24 21:50 UTC, zak-pawel requested changes

2021-02-24 21:50 UTC, zak-pawel commented on plugins/inputs/csgo/csgo.go
> +  ## specify servers using the following format:
`Specify`

2021-02-24 21:50 UTC, zak-pawel commented on plugins/inputs/csgo/README.md
> +```
`SampleConfig must match the readme, but not include the plugin name.` -> https://github.com/influxdata/telegraf/wiki/Review

Please, copy here content of `sampleConfig` from `csgo.go`

2021-02-24 21:50 UTC, zak-pawel commented on plugins/inputs/csgo/csgo.go
> +	if len(server) != 2 {
New line for better readability?

2021-02-24 21:50 UTC, zak-pawel commented on plugins/inputs/csgo/csgo.go
> +		return errors.New("wrong argument length")
Can you elaborate on that in this error?

2021-02-24 21:50 UTC, zak-pawel commented on plugins/inputs/csgo/csgo.go
> +func request_server(url string, rconPw string) (string, error) {
Use camelCase.

2021-02-24 21:50 UTC, zak-pawel commented on plugins/inputs/csgo/csgo_test.go
> +func request_mock(_ string, _ string) (string, error) {
camelCase.

2021-02-24 21:50 UTC, zak-pawel commented on plugins/inputs/csgo/csgo.go
> +	cpu, err := strconv.ParseFloat(fields[0], 32)
Check `if len(fields) == 10`

2021-03-01 19:45 UTC, zak-pawel approved these changes

2021-03-02 22:07 UTC, Jagularr commented on plugins/inputs/csgo/csgo.go
> +		return errors.New("incorrect server config")
might want to make this more descriptive of the issue

2021-03-02 22:10 UTC, Jagularr commented on plugins/inputs/csgo/csgo.go
> +		return errors.New("bad response")
same here, more specificity in the messages might be helpful for the user.

2021-03-02 22:12 UTC, Jagularr commented on plugins/inputs/csgo/csgo.go
> +type statsData struct {
nitpick but `statsData` is redundant, `stats` is as good of a name.

2021-03-02 22:15 UTC, Jagularr commented on plugins/inputs/csgo/csgo.go
> +	}
if you want to get rid of this really long block of almost duplicated code, you could stick it in a loop and add each entry to a separate float64 slice, and then use each index of that slice, respectively, when you create the `stats` object below.

2021-03-02 22:16 UTC, Jagularr reviewed
Overall looks good, minor comments.

2021-03-03 19:05 UTC, ssoroka approved these changes
I'm going to merge and you can address Jagularr's feedback in a subsequent PR.

2021-03-03 19:05 UTC, merged