Tail glob
influxdata/telegraf pull request #8613
Opened 2020-12-22 18:00 UTC by sspaink

### Required for all PRs:

- [x] Signed [CLA](https://influxdata.com/community/cla/).
- [x] Associated README.md updated.
- [x] Has appropriate unit tests.

Resolve issue #7419 by converting `[!` to `[^` which allows both characters to be used.

The Tail plugin depends on the standard Go function [filepath.Glob](https://golang.org/pkg/path/filepath/#Glob) which uses [filepath.Match](https://golang.org/pkg/path/filepath/#Match) and this function does not support `!` only `^`, evidently this was an oversight during implementation: https://github.com/golang/go/issues/41394. Hopefully in the second version of the filepath package both characters will be supported natively and we can remove this change.

Also updated the relevant unit test in globpath_test.go to use table driven tests.

Thanks!

2020-12-23 21:41 UTC, Jagularr approved these changes
Makes sense to me.

2021-01-04 13:00 UTC, srebhan commented on internal/globpath/globpath.go
> +	g.path = strings.Replace(g.path, "[!", "[^", -1)
Can we please use
```suggestion
	g.path = strings.ReplaceAll(g.path, "[!", "[^")
```

2021-01-04 13:04 UTC, srebhan reviewed
Would love to use `ReplaceAll()` instead of the `Replace()` function with `-1` for readability. Furthermore, `\\[!` is a valid pattern matching literal `[!` but is now replaced to `\\[^` with your change. Even though I think it is unlikely to be used in the wild, the probability is not zero. Could you please check this corner-case!?

2021-01-04 18:12 UTC, sspaink commented
@srebhan thanks for the review! So because Go doesn't support [negative lookahead](https://stackoverflow.com/questions/26771592/negative-look-ahead-in-go-regular-expressions) in regular expressions I am having a hard time thinking of a clean way to check for this edge case, do you have any suggestions?

2021-01-05 10:20 UTC, srebhan commented
Well 
```
	re := regexp.MustCompile(`(?:[^\\])(\[!)`)
	re.ReplaceAllString(s, "[^")
```
should work according to [my test](https://play.golang.org/p/ei1qPz6fqD9)...

2021-01-07 17:24 UTC, sspaink commented
@srebhan So I couldn't get the regex to work exactly like we would want to. I did find another open source project [doublestar](https://github.com/bmatcuk/doublestar) that supports both double star and !/^ for negation, it does remove the custom logic that globpath has for handling doublestar which is nice. What do you think?

@Jagularr the code has changed quite a bit from when you reviewed it after my latest change in case you wanted to look at it again as well.

2021-01-14 18:08 UTC, ssoroka requested changes

2021-01-14 18:08 UTC, ssoroka commented on plugins/inputs/phpfpm/phpfpm_test.go
> +	assert.Equal(t, `socket doesn't exist "/tmp/invalid.sock": <nil>`, err.Error())
should not be nil. remove error from internal error format.

2021-01-14 18:08 UTC, ssoroka commented on plugins/inputs/tail/README.md
> +  ## See https://github.com/gobwas/glob and https://golang.org/pkg/path/filepath/#Match for more examples
add note about `**/**`

2021-01-14 18:12 UTC, ssoroka commented
replace `**` with `**/**` for backwards compatibility

2021-01-18 14:48 UTC, srebhan commented
@sspaink what's wrong with the regexp I posted? Could you give me an example where it fails!? Requiring an external dependency to replace a regexp seems odd...

2021-01-19 15:53 UTC, sspaink commented
@srebhan The two issues I noticed when you run the playground example you provided: `lala[!w]ee --> lal[^w]ee` the result overrides the 'a' in the second 'la' and then if there isn't any characters trailing the negation class it doesn't update: `[!p]laid --> [!p]laid`.

@ssoroka provided a regex that solved the second issue, [playground](https://play.golang.org/p/lhgw5uskGKP) but the first problem where the previous character gets replaced still happens.

2021-01-19 16:07 UTC, ssoroka commented on plugins/inputs/tail/README.md
> +  ##   "/var/log/**/*.log"   -> recursively find all .log files in /var/log and subdirectories
what if we do the replace `**` -> `**/**` ?

2021-01-19 16:10 UTC, ssoroka commented
re using a library, glob is used in a lot of different places and I'd really love consistent behavior that–ideally–meet some standard that we are not managing ourselves. It seems too easy to accidentally create our own fork of glob behavior, which it seems is exactly what we've done and now we have to support this old broken behavior...

2021-01-19 16:11 UTC, ssoroka commented on plugins/inputs/tail/README.md
> +  ##   "/var/log/**/*.log"   -> recursively find all .log files in /var/log and subdirectories
I guess the only potential concern there is not to replace existing `**/**` with `**/**/**/**`, which I believe implies a minimum number of directories descended. for matches

2021-01-22 09:12 UTC, srebhan commented
@sspaink fixed both with
```golang
package main

import (
	"fmt"
	"regexp"
)

func main() {
	test := []string {
		"lala[!w]ee",
		"[!p]laid",
		"foo\\[!wja",
		"\\[!wbar",
		"foo[!abc] and \\[!wbar are wunderbar",
	}

	re := regexp.MustCompile(`([^\\]?)(\[!)`)
	for _, s := range test {
		fmt.Printf("%s --> %s\n", s, re.ReplaceAllString(s, "$1[^"))
	}
}
```
But if I understand @ssoroka correctly he prefers to use the doublestar-package. Also fine with me. :-)

2021-02-09 20:28 UTC, sspaink commented
@srebhan thank you for the updated regular expression, I've updated the pull request to use the suggested change and it looks like it works without having to change any of the existing tests.
@ssoroka I did like the idea of moving to the library but I couldn't figure out how to cleanly replace **->**/** without causing the issue you describe (**/**->**/**/**/**). Maybe we can move this to a library safely for a 2.0 release.

2021-02-10 09:44 UTC, srebhan approved these changes
Looks good to me.

2021-02-16 21:34 UTC, ssoroka approved these changes

2021-02-16 21:53 UTC, merged