Add Starlark parsing example of nested JSON
influxdata/telegraf pull request #8675
Opened 2021-01-11 20:22 UTC by samhld

### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2021-01-12 16:43 UTC, Jagularr approved these changes

2021-01-20 10:17 UTC, srebhan commented on plugins/processors/starlark/testdata/json_nested.star
> +Example input: ```
Has to be 
```suggestion
Example Input: ```
```

2021-01-20 10:19 UTC, srebhan commented on plugins/processors/starlark/testdata/json_nested.star
> +Example input: ```
Furthermore I'm not sure if the current implementation of the test can cope with multi-line input. AFAIK we read one input per line, so please remove the nice formatting and make it an ugly one-liner. Never thought I will say this ever... ;-)

2021-01-20 12:12 UTC, srebhan commented on plugins/processors/starlark/testdata/json_nested.star
> +Example input: ```
Last but not least the given input/output has to be in line-protocol format... Please fix those issues to keep the starlark test-suite working...

2021-01-20 12:13 UTC, srebhan commented on plugins/processors/starlark/testdata/json_nested.star
> +Example output:
Has to be `Example Output`.

2021-01-20 12:14 UTC, srebhan requested changes
The starlark testdata directory contains testable examples. To run those tests the `Example Input` and `Example Output` have to be in influx-line-protocol format. Please fix those. Code looks good.

2021-02-15 16:32 UTC, srebhan approved these changes
Thank you very much!

2021-02-16 02:16 UTC, samhld commented
@srebhan this commit shouldn't have been part of the PR.  I still need to make the changes you mentioned to this one.  I crossed PRs accidentally.

2021-02-16 08:12 UTC, srebhan commented
@samhld you can still change the PR and force-push it to replace it completely. I will remove the "ready-to-merge" flag for the time being. Please tell me once you are ready...

2021-02-17 01:21 UTC, samhld commented
ok @srebhan this one should be good to go too!

2021-02-17 10:10 UTC, srebhan commented on plugins/processors/starlark/testdata/json_nested.star
> +load("logging.star", "log")
I guess this is not required anymore!?

2021-02-17 10:26 UTC, srebhan reviewed
Please remove the import of `logging.star`. Otherwise it's good to go.

2021-03-05 10:53 UTC, srebhan commented
@samhld any news on this?

2021-03-05 16:52 UTC, samhld commented
@srebhan Missed this, sorry!  Done.

2021-03-09 16:24 UTC, merged