Add SNMP examples to readme
influxdata/telegraf pull request #8807
Opened 2021-02-04 20:08 UTC by sjwang90

Used your sample config @kiler129 for the first example

2021-02-04 20:22 UTC, Hipska commented
What is the goal of this? The README file already has more complete examples than the one added?

2021-02-04 21:22 UTC, sjwang90 commented
@Hipska There's been requests for more real world examples for the SNMP plugin #7433. I wanted to create a folder where people can add useful examples and link it from the readme. 

This single device example was one of the basic ones mentioned. If you think it's redundant, we can remove it.

2021-02-04 21:39 UTC, Hipska commented
It's a good idea, but that example is just too simple, it only provides the system uptime. For real world examples I would at least expect one of cpu/memory/disk/temperature/interface stats.

2021-02-04 23:54 UTC, sjwang90 commented
Do you have any real-world examples you'd like to share? I'm totally good with getting rid of this PR since it wouldn't be that useful.

2021-02-05 09:42 UTC, Hipska requested changes

2021-02-05 09:42 UTC, Hipska commented on plugins/inputs/snmp/README.md
> +- [Single device](https://github.com/influxdata/telegraf/blob/snmp-examples/plugins/inputs/snmp/testdata/single-device.conf)
I don't think that's a good link.
```suggestion
- [Single device](testdata/single-device.conf)
```

2021-02-05 09:44 UTC, Hipska commented
I think I could forge some, but the problem actually is that each setup is very specific and most of the time, it isn't always purely snmp config, but also some processors to fix some data.

2021-02-05 23:20 UTC, sjwang90 commented
I think that's nice as well - if it's clear in the sample config to explain what the purpose of the processor is? Sample input and output data is always good.

2021-04-02 17:03 UTC, sjwang90 commented
@Hipska I'm going to close this - if you have any examples to add please do so! I'll assign you in the original issue. you are the SNMP master 👑

2021-04-02 17:03 UTC, closed without merging