kube_inventory: update label in RBAC example
influxdata/telegraf pull request #8836
Opened 2021-02-08 19:39 UTC by paulchoi

The label for `influx:cluster:viewer` ClusterRole is
`rbac.authorization.k8s.io/aggregate-view-telegraf: "true"`, but
telegraf-ds's Helm Chart expects role label of
`rbac.authorization.k8s.io/aggregate-view-telegraf-stats: "true".

For a better out-of-the-box experience, it should match the Helm chart
used by the customer base.

### Required for all PRs:

- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2021-02-09 19:28 UTC, helenosheaa requested changes

2021-02-09 19:28 UTC, helenosheaa commented on plugins/inputs/kube_inventory/README.md
> +    rbac.authorization.k8s.io/aggregate-view-telegraf-stats: "true"
Should we also update this inside the matchLabels on line 108?

2021-09-15 17:41 UTC, sspaink commented
Hello @paulchoi, do you still have time to work on this pr and can address @helenosheaa comment? Thanks!

2021-12-20 22:47 UTC, sjwang90 commented
Closing this PR due to inactivity. If @paulchoi or someone else is interested on taking this work back up, please feel free to re-open the PR.

2021-12-20 22:47 UTC, closed without merging