feat: implement nfsclient stats input plugin on linux to count kernel…
influxdata/telegraf pull request #8865
Opened 2021-02-16 15:12 UTC by write0nly

… nfs client side statistics per host

### Required for all PRs:

- [README.md](plugins/inputs/nfsstat/README.md) Associated README.md updated.
- [/] Has appropriate unit tests.

2021-03-09 10:44 UTC, srebhan commented
Thanks for submitting this. Can you please elaborate on how it is different than https://github.com/influxdata/telegraf/tree/master/plugins/inputs/nfsclient? 

In case it is different, can you please check if you can merge your code into this plugin to avoid having two plugins doing similar things...

2021-03-10 12:50 UTC, write0nly commented
> Thanks for submitting this. Can you please elaborate on how it is different than https://github.com/influxdata/telegraf/tree/master/plugins/inputs/nfsclient?
> 
> In case it is different, can you please check if you can merge your code into this plugin to avoid having two plugins doing similar things...

The reason I wrote this plugin instead of tagging along the mountstats one is because I believe that using mountstats is fraught with a large number of issues, and likely to give you results that can be easily mis-interpreted. eg:

1. mountstats counters are namespaced, so if you have docker containers (or just unshare -m) that mount nfs without doing a -v from the OS mount there will be innacurate counters, values that do not match, or mounts that are not accounted for.
2. if you run telegraf inside docker you may have a different and unexpected set of results.
3. even in the same namespace if you have 2 NFS mounts /mnt/1 and /mnt/2 that bind to the same vfsmount the counters will be the same for both so the metrics will show unexpected results. The note on the plugin page implies that this is a limitation of the metrics exposed by the kernel, however this is not really accurate as the counters should be per server:fsid not mountpoint:

>NOTE Many of the metrics, even if tagged with a mount point, are really per-server. Thus, if you mount these two shares: nfs01:/vol/foo/bar and nfs01:/vol/foo/baz, there will be two near identical entries in /proc/self/mountstats. This is a limitation of the metrics exposed by the kernel, not the telegraf plugin.

Therefore I would argue that you have 2 very different use cases that measure totally different things, and therefore should not be conflated together:

1. nfsstats, global counters from the kernel nfs client that will give you 100% accurate counters on all nfs operations done on the host via the kernel nfs code.
2. the input on #4615 based on mountstats , which will give you accurate measurements in a single namespace for a tuple (server, fsid), allows you to have per nfsmount stats, allows for latency and many other goodies that are not the scope of nfsstats.

I would argue that the name nfsclient for the plugin #4615 is innacurate, as it is actually nfsmount based, but I would not pursue this discussion. I would also argue that the points above should be added as notes to the other plugin, because it is likely to lead users into confusion and future issues unless they understand the peculiarities of the measurements in great detail.

2021-03-10 12:50 UTC, write0nly commented
> Thanks for submitting this. Can you please elaborate on how it is different than https://github.com/influxdata/telegraf/tree/master/plugins/inputs/nfsclient?
> 
> In case it is different, can you please check if you can merge your code into this plugin to avoid having two plugins doing similar things...

The reason I wrote this plugin instead of tagging along the mountstats one is because I believe that using mountstats is fraught with a large number of issues, and likely to give you results that can be easily mis-interpreted. eg:

1. mountstats counters are namespaced, so if you have docker containers (or just unshare -m) that mount nfs without doing a -v from the OS mount there will be innacurate counters, values that do not match, or mounts that are not accounted for.
2. if you run telegraf inside docker you may have a different and unexpected set of results.
3. even in the same namespace if you have 2 NFS mounts /mnt/1 and /mnt/2 that bind to the same vfsmount the counters will be the same for both so the metrics will show unexpected results. The note on the plugin page implies that this is a limitation of the metrics exposed by the kernel, however this is not really accurate as the counters should be per server:fsid not mountpoint:

>NOTE Many of the metrics, even if tagged with a mount point, are really per-server. Thus, if you mount these two shares: nfs01:/vol/foo/bar and nfs01:/vol/foo/baz, there will be two near identical entries in /proc/self/mountstats. This is a limitation of the metrics exposed by the kernel, not the telegraf plugin.

Therefore I would argue that you have 2 very different use cases that measure totally different things, and therefore should not be conflated together:

1. nfsstats, global counters from the kernel nfs client that will give you 100% accurate counters on all nfs operations done on the host via the kernel nfs code.
2. the input on #4615 based on mountstats , which will give you accurate measurements in a single namespace for a tuple (server, fsid), allows you to have per nfsmount stats, allows for latency and many other goodies that are not the scope of nfsstats.

I would argue that the name nfsclient for the plugin #4615 is innacurate, as it is actually nfsmount based, but I would not pursue this discussion. I would also argue that the points above should be added as notes to the other plugin, because it is likely to lead users into confusion and future issues unless they understand the peculiarities of the measurements in great detail.

2021-03-25 20:54 UTC, ssoroka requested changes
It'd be good to also update the docs of both plugins with some of the context from your comments on the issue to help users decide which plugin to use.

2021-03-25 20:54 UTC, ssoroka commented on plugins/inputs/nfsstat/nfsstat.go
> +	return "[[inputs.nfsstat]]"
SampleConfig() shouldn't include the name of the plugin
```suggestion
	return ""
```

2021-03-25 20:54 UTC, ssoroka commented on plugins/inputs/nfsstat/nfsstat.go
> +			return []int64{}, err
do you want to return only the counters that parsed correctly?

2021-03-25 20:54 UTC, ssoroka commented on plugins/inputs/nfsstat/nfsstat.go
> +		return []int64{}, err
Can return nils instead of empty slices. `len(nil) == 0` anyway.
```suggestion
		return nil, err
```

2021-03-25 20:54 UTC, ssoroka commented on plugins/inputs/nfsstat/nfsstat.go
> +		return err
don't need to log as well as return. if you want the extra context use 
```suggestion
		return fmt.Errorf("reading /proc/net/rpc/nfs: %w", err)
```

2021-08-31 21:15 UTC, helenosheaa commented
@write0nly thanks for the PR. Are you still working on this? There's some review comments we'd like to get clarified before we proceed.

2021-11-04 17:18 UTC, sjwang90 commented
Closing this PR due to inactivity. If someone is interested on taking this work back up, please feel free to re-open the PR and take over the code.

2021-11-04 17:18 UTC, closed without merging