add XML examples
influxdata/telegraf pull request #9097
Opened 2021-04-06 20:20 UTC by sjwang90

added XML examples:
- cdc COVID-19 vaccine HTTP/XML config 
- London bikeshare XML file
- London bikeshare file/XML config

2021-04-07 13:15 UTC, Jagularr approved these changes

2021-04-08 07:40 UTC, srebhan commented on plugins/parsers/xml/testcases/cdc-vaccines.conf
> +            2nd_dose_allocations = "_2nd_dose_allocations"
Not completely sure, but shouldn't this have the same indention level as `data_format` and `tagexclude`?

2021-04-08 07:46 UTC, srebhan commented on plugins/parsers/xml/testcases/cyclehire-london.conf
> +      placement = "string(temporary)"
The test-cases (unfortunately) have another format. You should do:
```suggestion

metric_selection = "response/child::location"
metric_name = "string('bikes')"

timestamp = "/stations/@lastUpdate"
timestamp_format = "unix_ms"

field_selection = "child::info"
field_name = "name(@*[1])"
field_value = "number(@*[1])"

[tags]
  address = "@name"
  id = "@id"

[fields]
  placement = "string(temporary)"
```

2021-04-08 07:50 UTC, srebhan requested changes
Hey Samantha, the test-case format is only a simplified version of the telegraf config and _only_ contains the parser's part without prefixes and can only read local files. Please take a look at my comment regarding the second test-case.

Furthermore, I fear that, due to these limitations, you cannot represent your first test case as is. You might download one of those XML files and put it locally and then parse it without the `enum` processor to generate a testable test-case.

Additionally or alternatively, we might want to generate an _examples_ subdir in the `xml` parser where you can put those full configs and then add a link to the parser's readme. What do you think?

2021-04-12 20:56 UTC, sjwang90 commented
As discussed on slack, instead of creating a separate `examples` folder we can just add them to our customer facing docs - docs.influxdata.com

2021-04-12 20:56 UTC, closed without merging