Add option for loki to use system timestamp
influxdata/telegraf pull request #9114
Opened 2021-04-09 21:24 UTC by loganmc10

### Required for all PRs:

- [x] Updated associated README.md.
- [ ] Wrote appropriate unit tests.

Loki has very strict ordering requirements. You cannot submit a log line with a timestamp older than what already exists (for a matching label set).

I've been getting HTTP 400 errors from the Loki output plugin (SNMP trap input). I added a file output and I noticed that items are written to the file slightly out of order (timestamps are not always ascending).

This change adds an option (system_timestamp) to the Loki output plugin to allow it to use the system timestamp in the Loki message, rather than the metrics provided timestamp. This should mean that timestamp values are always ascending.

@Eraac since you wrote the original Loki plugin

2021-04-09 21:25 UTC, loganmc10 commented
!signed-cla

2021-04-12 13:12 UTC, Jagularr approved these changes

2021-04-13 14:15 UTC, ssoroka requested changes
Why hasn't CI ran on this branch?

2021-04-13 14:35 UTC, loganmc10 commented
Fair enough, I didn't realize there was a processor that could modify the timestamp of a metric, thanks for the info

2021-04-13 14:35 UTC, closed without merging