Add UTF-8 sanitizer to Strings plugin
influxdata/telegraf pull request #9118
Opened 2021-04-12 18:33 UTC by loganmc10

### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.

resolves #9113

Adds a new option for the Strings processer to sanitize strings so that they conform to utf-8

2021-04-12 19:42 UTC, Jagularr approved these changes
this makes sense to me!

2021-04-12 19:42 UTC, ssoroka approved these changes

2021-04-13 21:34 UTC, jessingrass requested changes

2021-04-13 21:34 UTC, jessingrass commented on plugins/processors/strings/README.md
> +  #   new = ""
Could you change `new` to `replacement`? New does not describe what is happening in this code.

2021-04-13 21:34 UTC, jessingrass commented on plugins/processors/strings/README.md
> +  ## Sanitize a string to ensure it is a valid utf-8 string. Non-valid characters are replaced by 'new'
Could you clarify your description to align more closely with the go documentation around ToValidUTF8 function docs? Here's a link to the relevant documentation and description: https://golang.org/pkg/strings/#ToValidUTF8

2021-04-13 23:17 UTC, loganmc10 commented
Ok I've incorporated that feedback

2021-04-29 20:46 UTC, sspaink commented
!retry-checks

2021-04-29 21:04 UTC, sspaink commented
@loganmc10 not sure why the CI didn't trigger for this pull request. Would you be able to push an empty commit to see if it would trigger it? You can use `git commit -m 'empty commit' --allow-empty`

2021-04-29 21:17 UTC, loganmc10 commented
@sspaink ok done, it does look a little more normal now? I never saw this workflow approval gate before

2021-04-30 00:46 UTC, merged