added is_active parameter to snmp input plugin
influxdata/telegraf pull request #9153
Opened 2021-04-20 08:05 UTC by denizzengin

### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.

resolves #

2021-04-20 13:42 UTC, Jagularr requested changes
Thanks for the PR! It's not very clear what `is_active` means (does it simply enable or disable an input plugin?), if so, it should be better documented in the config, and not linked with SNMP only in any way, as it doesn't seem unique to SNMP.

2021-04-20 13:59 UTC, denizzengin commented
> Thanks for the PR! It's not very clear what `is_active` means (does it simply enable or disable an input plugin?), if so, it should be better documented in the config, and not linked with SNMP only in any way, as it doesn't seem unique to SNMP.

Yes, it is only enable or disable config (specially multiple config). I implemented only snmp side so linked with SNM plugin but as i said it can be support others with simple implementation 
Also, i think if we use this parameter below, it's fairly simple that means load or not a config file.
[[inputs.xxx]] 
is_active = true/false

2021-05-04 21:12 UTC, reimda commented
Hi @denizzengin. I don't think I understand the problem you're trying to solve. What benefit does this new setting have over commenting out the plugin section in the config?

2021-05-05 05:34 UTC, denizzengin commented
> Hi @denizzengin. I don't think I understand the problem you're trying to solve. What benefit does this new setting have over commenting out the plugin section in the config?

Hi @reimda. Lets talk our needs,
 We have multiple separated device config in telegraf.d config directory. We also have a outer service and it updates or deletes config file and reload config. So  we collect metrics but at the same time, we need to make inactive  device config file for a while. We don't want to delete config and recreate because it can be limited time and just want to update above is_active parameter.

Actually, I added extra comment because this implementation only snmp input. If someone wants to add as same as mine in the future, I think it can be helpful. 
thanks for review.

2021-05-26 13:17 UTC, closed without merging