added cli help file and linked file to readme
influxdata/telegraf pull request #9257
Opened 2021-05-11 13:56 UTC by jessingrass

Documentation updates adding command line help options to new file, linked from readme.

2021-05-11 21:05 UTC, ssoroka requested changes
this is already in internal/usage.go as well as scattered in cmd/telegraf/telegraf.go, and I'd like to avoid making another copy of it. 
(Also this is not well-formatted markdown)
Suggesting we close this and link to internal/usage.go instead.

2021-05-17 13:02 UTC, Hipska commented
Yeah indeed, the usage.go and usage_windows.go are sufficient I think. So a clickable link to those files could be placed in `docs/COMMAND_LINE_OPTIONS.md` as well as in `cmd/telegraf/README.md`.

2021-05-18 16:04 UTC, reimda approved these changes

2021-09-15 23:29 UTC, sjwang90 commented
Looks like i added similar documentation and helen brought up the same concerns. I'll close this PR and we'll decide if it's still redundant to include in this PR https://github.com/influxdata/telegraf/pull/9635

2021-09-15 23:29 UTC, closed without merging