feat: set user agent when scraping prom metrics
influxdata/telegraf pull request #9271
Opened 2021-05-13 20:04 UTC by russorat

### Required for all PRs:

- [ ] Updated associated README.md.
- [ ] Wrote appropriate unit tests.

this change updates the user agent used when scraping a prometheus endpoint from the generic Go-Http-Client to Telegraf/1.18 used in other plugins (the influxdb_v2 output)

2021-05-17 12:48 UTC, Hipska approved these changes

2021-05-17 12:48 UTC, Hipska commented on plugins/inputs/prometheus/prometheus.go
> +
```suggestion
```

2021-05-17 18:55 UTC, Hipska approved these changes

2021-05-18 21:12 UTC, reimda requested changes

2021-05-18 21:12 UTC, reimda commented on plugins/inputs/prometheus/prometheus.go
> +		req.Header.Set(header, value)
The code called req.Header.Add() before but now it calls req.Header.Set(). Any reason for the change? If not, let's switch back to Add to be compatible with the previous code.

2021-05-18 21:56 UTC, russorat commented on plugins/inputs/prometheus/prometheus.go
> +		req.Header.Set(header, value)
I was just copying some other addHeaders code. all good.

```suggestion
		req.Header.Add(header, value)
```

2021-05-20 14:36 UTC, reimda approved these changes

2021-05-20 14:36 UTC, merged