HTTP basic auth for webhooks
influxdata/telegraf pull request #9332
Opened 2021-06-04 18:11 UTC by akrantz01

### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.

resolves #6023 

Adds support for HTTP basic auth in webhooks where each webhook type to have a different username and password.

2021-06-04 18:52 UTC, ssoroka requested changes
I think for something so relevant to many plugins, I'd like to see it have its own folder for `auth` in the common folder, and I'd like to see support for more auth types in addition to Basic, specifically api key and maybe bearer token.

2021-06-04 18:52 UTC, ssoroka commented on plugins/inputs/webhooks/common/basic_auth.go
> +		subtle.ConstantTimeCompare([]byte(password), []byte(b.Password)) == 1
you will want to make sure both of these execute, not just one, otherwise a timing attack can easily figure out which usernames are valid

2021-06-04 18:52 UTC, ssoroka commented on plugins/inputs/webhooks/common/basic_auth_test.go
> +}
missing negative test cases

2021-06-04 19:09 UTC, akrantz01 commented
Should I be adding API key and bearer token auth along with this PR, or should it be a separate issue?

2021-09-07 21:41 UTC, sspaink requested changes

2021-09-07 21:41 UTC, sspaink commented on plugins/common/auth/basic_auth.go
> +	Password string
```suggestion
	Username string `toml:"username"`
	Password string `toml:"password"`
```

2022-03-03 20:06 UTC, powersj commented
Hey @akrantz01! hope you are well - any interest in resolving conflicts and landing this still? Thanks!

2022-03-04 02:36 UTC, akrantz01 commented
Sure! All the merge conflicts should be resolved now

2022-03-04 13:40 UTC, powersj approved these changes

2022-03-04 15:50 UTC, sspaink approved these changes

2022-03-04 15:51 UTC, merged