Add include_nodes filter for jenkins
influxdata/telegraf pull request #9351
Opened 2021-06-10 19:18 UTC by akrantz01

### Required for all PRs:

- [x] Updated associated README.md.
- [x] Wrote appropriate unit tests.

resolves #9047 

Adds the ability to explicitly include nodes for the `jenkins_node` metric. Previously, you could only exclude nodes from being collected.

Like the `job_exclude` and `job_include` filters, `node_exclude` takes precedence over `node_include` if they are both present.

2021-06-10 22:02 UTC, akrantz01 commented
@G0lang Would you be willing to test this?

2021-06-28 19:23 UTC, srebhan requested changes
@akrantz01 thanks for this PR, it makes totally sense. However, you probably should use `NewIncludeExcludeFilter()` of the filter package which does the include/exclude handling for you and reduces the amount of code.

2021-06-29 07:03 UTC, srebhan approved these changes
Looks good to me. Thanks for also tackling `jobFilter`! I have just one minor comment in the code, but it is optional.

2021-06-29 15:36 UTC, akrantz01 commented on plugins/inputs/jenkins/jenkins.go
> +	if j.nodeFilter != nil && !j.nodeFilter.Match(tags["node_name"]) {
Oh, you're right; I didn't even realize.

2021-06-30 06:20 UTC, srebhan approved these changes
Perfect, thank you! LGTM.

2021-07-01 20:54 UTC, MyaLongmire approved these changes

2021-07-01 20:54 UTC, merged