Fix RabbitMQ regression in #9383
influxdata/telegraf pull request #9443
Opened 2021-06-28 16:26 UTC by srebhan

### Required for all PRs:

- [X] Updated associated README.md.
- [X] Wrote appropriate unit tests.

resolves #9383 

This resolves the wrong types for `_avg` metrics. Those errors went unnoticed before checking the return types (#8992) and returned invalid values (all zero) if the server responded with as floating-point formatted number by chance.
This PR furthermore tries to handle missing plugins (e.g. `federation`) more gracefully providing the server sent error to the user. To avoid those errors altogether, a (backward-compatible) metric-filter is introduced such that the user can disable erroneous metrics.

2021-06-28 19:56 UTC, akrantz01 requested changes
Overall LGTM. I just left some comments on some of the type conversion for `Memory.Total`.

2021-06-29 06:38 UTC, srebhan commented on plugins/inputs/rabbitmq/rabbitmq.go
> +				case map[string]interface{}:
Unfortunately, this does not work as the JSON decoder will return a `map[string]interface{}`.

2021-06-29 06:49 UTC, srebhan commented on plugins/inputs/rabbitmq/rabbitmq.go
> +						acc.AddError(fmt.Errorf("no known memory estimation in %v", v))
Done. Simplified the whole estimator thing, so I think we avoid this issue now with less code. :-)

2021-06-29 06:50 UTC, srebhan commented on plugins/inputs/rabbitmq/rabbitmq.go
> +					fields["mem_total"] = v
I take your work on it. ;-) Changed.

2021-06-29 13:29 UTC, srebhan commented
@akrantz01 thanks for review. I changed the code according to your suggestions except for the `map[string]interface{}` part, which does not work otherwise.

2021-06-29 15:26 UTC, akrantz01 approved these changes

2021-06-29 21:01 UTC, sspaink approved these changes

2021-06-29 21:01 UTC, merged