docs: update caddy server instructions
influxdata/telegraf pull request #9698
Opened 2021-08-31 17:50 UTC by sjwang90

Existing Prometheus plugin docs for "Usage for Caddy Server" is for Caddy v1 and out of date as now Caddy no longer has a prometheus plugin and metrics are built in. 

Updating readme to include new instructions and links

2021-08-31 18:41 UTC, sjwang90 commented
@olivierlambert You submitted the initial instructions a few years ago. Would you mind reviewing this docs PR?

2021-09-16 21:27 UTC, sspaink requested changes

2021-09-16 21:27 UTC, sspaink commented on plugins/inputs/prometheus/README.md
>  If you want to monitor Caddy, you need to use Caddy with its Prometheus plugin:
Can you remove the mention of the Prometheus plugin here?

2021-09-16 21:27 UTC, sspaink commented on plugins/inputs/prometheus/README.md
>  > This is the default URL where Caddy Prometheus plugin will send data.
Here too.

2021-09-21 16:06 UTC, powersj approved these changes

2021-09-21 19:03 UTC, sspaink approved these changes

2021-09-21 19:03 UTC, merged