docs: Move nightly builds
influxdata/telegraf pull request #9747
Opened 2021-09-13 13:33 UTC by popey

- [X] Updated associated README.md.
- [ ] Wrote appropriate unit tests.
- [X] Pull request title or commits are in [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/#summary) (e.g. feat: or fix:)

Discussed in a Telegraf planning meeting last week. 

Make sure to link issues and using a keyword like "resolves #1234".
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
-->

resolves #

2021-09-14 13:00 UTC, srebhan requested changes
Hey @popey, good idea. However, I guess you forgot to remove the initial links to the nightly build from README.md, didn't you?

2021-09-14 13:07 UTC, srebhan approved these changes
Looks perfect to me. Thanks @popey!

2021-09-14 13:33 UTC, sspaink requested changes

2021-09-14 13:33 UTC, sspaink commented on README.md
> +[Nightly])(/docs/NIGHTLIES.md) builds are available, generated from the master branch.
```suggestion
[Nightly](/docs/NIGHTLIES.md) builds are available, generated from the master branch.
```

2021-09-14 13:33 UTC, sspaink commented on docs/README.md
> +[nightlies]: /docs/NIGHLIES.md
```suggestion
[nightlies]: /docs/NIGHTLIES.md
```

2021-09-16 17:19 UTC, powersj approved these changes
I merged @sspaink suggestions and I'm +1. @sspaink can you want to re-review and merge if you are happy with this?

2021-09-16 17:22 UTC, sspaink approved these changes

2021-09-16 17:22 UTC, merged